### ISSUE TITLE
how to obtain method

### ISSUE THREAD

**Issue by tywo45** [classgraph/classgraph#229] opened 2018-08-03 09:28 UTC
`Method method = clazz.getMethod(methodName, parameterTypes);`

how did i obtain parameterTypes, thanks!

**Comment by lukehutch** [comment] 2018-08-03 14:03
Hi,

```java
ScanResult scanResult = new ClassGraph()
   .whitelistPackages(package)
   .enableClassInfo()
   .enableMethodInfo()
   .scan();
    
ClassInfo ci = scanResult.getClassInfo(className);
if (ci != null) {
    for (MethonInfo mi : ci.getMethodInfo()) {
        MethodParameterInfo mpi = mi.getMethodParameterInfo();
        //... 
    } 
} 
```

I'm typing on my phone... I hope that's correct :) Made let me know how you get on.

**Comment by lukehutch** [comment] 2018-08-03 14:08
(Edit: fixed a couple of errors in the above code)

**Comment by lukehutch** [comment] 2018-08-03 14:13
You can also call `MethonInfo[] mis = ci.getMethodInfo(methodName)` to get all methods with a given name (with different parameter types).

**Comment by lukehutch** [comment] 2018-08-04 09:43
I'll close this since it's not a bug. Feel free to ask more questions in the Gitter room for ClassGraph:

https://gitter.im/classgraph/Lobby

**Closed by lukehutch** 2018-08-04 09:43 UTC
