### ISSUE TITLE
Unable to process Jar entry [module-info.class] for annotations

### ISSUE THREAD

**Issue by muratme** [classgraph/classgraph#291] opened 2018-12-12 06:59 UTC
**Java-Version:**

_java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)_

**Tomcat-Version**
_Apache Tomcat Version 8.5.8_

**OS**
_MacOS High Sierra v10.13.6_

> This appears to be an issue is related to the new Java 9 implementation added in this version, where I believe that the cause is due to how Java 9 is interacting with Tomcat, calling objects that do not yet exist until they upgrade Java and/or Tomcat.

```
Dec 12, 2018 8:40:28 AM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/sahibinden/repo/services/sahibinden-web/target/sahibinden-web/WEB-INF/lib/classgraph-4.6.7.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:133)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:60)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:209)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:119)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2125)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2001)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1967)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1952)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1326)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:878)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:369)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5269)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:622)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:569)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:828)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$254(TCPTransport.java:683)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$1/1163762658.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lukehutch** [comment] 2018-12-12 07:49
Constant pool tag 19 is only present in a module descriptor (`module-info.class` file). This bug indicates that Tomcat BCEL cannot yet handle the JDK 9+ bytecode format. This is not a ClassGraph bug, but it is caused by the fact that ClassGraph includes a class that is only supposed to be opened or loaded in JDK 9+. The version of Tomcat you're running doesn't know that `module-info.class` is a special classfile, and is trying to load and scan all classes, hence the crash.

This is reported by others too, in situations nothing to do with ClassGraph:

https://stackoverflow.com/questions/50567687/getting-invalid-byte-tag-in-constant-pool-19

In fact the latest version of Tomcat does only support JDK 8:

http://tomcat.apache.org/whichversion.html

This same exact thing happened when JDK 8 was released, and people were trying to load JDK 8 classes with Tomcat 7, but JDK 8 added new constant tag type 15 (method handle):

https://stackoverflow.com/questions/23541532/org-apache-tomcat-util-bcel-classfile-classformatexception-invalid-byte-tag-in

There's a solution here if you don't need annotations:

https://stackoverflow.com/a/12730059/3950982

If you do need annotations, you can create a custom version of the classgraph jar, where you just delete the `module-info.class` file from the root of the jar.

The correct long-term solution is to file a bug with Tomcat BCEL to ignore `module-info.class` (and `package-info.class` too, while you're at it):

http://tomcat.apache.org/bugreport.html

In future versions of ClassGraph, the `module-info.class` file will be moved to `META-INF/versions/9`, which should minimize the number of cases where other (non-ClassGraph) classpath scanners try to read `module-info.class` but don't know how to parse it. (This requires the scanner to ignore everything in `META-INF`, which many scanners probably didn't think to do, so it may or may not fix your situation.) ClassGraph is waiting on the next release of Moditect to move the module descriptor in this way:

https://github.com/moditect/moditect/issues/67

**Comment by lukehutch** [comment] 2018-12-12 07:51
Closing, since this is not a ClassGraph bug. Thanks for the report though!

**Closed by lukehutch** 2018-12-12 07:51 UTC

**Comment by lukehutch** [comment] 2019-01-04 20:53
Version 4.6.11 puts the `module-info.class` at `META-INF/versions/9`, which may solve this problem for some older libraries. Can you please test and let me know if it fixes the problem for you? Thank you.
