### ISSUE TITLE
ScanResult's JSON does not contain the default values of the annotation parameters

### ISSUE THREAD

**Issue by zhgzhg** [classgraph/classgraph#584] opened 2021-10-17 23:40 UTC
Greetings,

In ClassGraph 4.8.128 the ScanResult's JSON doesn't contain the annotation parameters' default values. This is problematic on environments which don't support `RetentionPolicy.RUNTIME` like Android.

If I have there for e.g.
```
@Retention(RetentionPolicy.RUNTIME)
@interface MyAnnotation { 
  String msg() default "helloWorld";
}

@MyAnnotation
class MyClass { }
```
trying to load the `msg`'s value for `MyClass` from the ScanResult initialized from the JSON brings no results.

**Comment by lukehutch** [comment] 2021-10-18 05:05
Thanks for the report, I'll take a look.

Out of curiosity, how are you using the JSON serialization of ScanResult? I was under the impression that nobody (or almost nobody) was actually using this feature, so I was going to remove this feature in the next major version of ClassGraph, since it required a lot of complex code to implement a custom serializer and deserializer within ClassGraph.

**Comment by lukehutch** [comment] 2021-10-18 05:20
I checked the JSON output from the example you gave, and the default parameter value is in fact contained in the JSON. Note that the default values are stored in the ClassInfo object for the `MyAnnotation` class, and *not* in the annotated class, `MyAnnotation`.

```
    {
      "__ID": "io.github.classgraph.json.AnnotationDefaultVals$MyAnnotation",
      "annotationDefaultParamValues": [
        {
          "name": "msg",
          "value": {
            "stringValue": "hello"
          }
        }
      ],
```

I also just added a unit test which shows that the annotation default parameter values are in fact correctly preserved across serialization followed by deserialization.

Can you please provide a complete example that will allow me to reproduce the problem you have observed?

**Comment by zhgzhg** [comment] 2021-10-18 23:18
Thank you for your quick answer! And indeed it is working fine!

After further investigation it turned out I was mislead by an incompletely overridden class path. What I didn't take into account was annotations in one JAR file, and code annotated with them in another JAR. As a result the JSON scan is mentioning the annotation used on the scanned classes, and it locally contains the values of the non-default annotation parameters, as they are found on the spot (... annotationInfo ->annotationParamValues). And the omitted (default) parameter values couldn't be resolved because the actual annotation was not really scanned.

On your question: I'm using the serialized ScanResult to achieve annotation-based dependency injection on the Android platform.

**Comment by lukehutch** [comment] 2021-10-19 01:25
Great, I'll close the issue.

Please let me know though, since I'm considering removing the JSON serialization support: how much work would it be for you to write the information you need from a `ScanResult` to a custom file format, rather than serializing the whole `ScanResult` to JSON? (I suspect in most cases if people are serializing the `ScanResult`, they need only a small subset of the total information contained in the `ScanResult` and all reachable objects.)

**Closed as completed by lukehutch** 2021-10-19 01:25 UTC
