### ISSUE TITLE
Why is ClassGraph so much slower then ClassPathScanningCandidateComponentProvider?

### ISSUE THREAD

**Issue by oliveryasuna** [classgraph/classgraph#796] opened 2023-09-29 02:28 UTC
Had a new case at work where I needed to perform classpath scanning. I set it up with Spring's `ClassPathScanningCandidateComponentProvider`, but my boss then told me to use ClassGraph since we already use it elsewhere. My boss was surprised to find that `ClassPathScanningCandidateComponentProvider` performed 10x faster then ClassGraph. Super simple scan in a package with no sub-packages, containing about 50 classes (all matches by the way). Am I doing something wrong or is ClassGraph just this slow?

Method using ClassGraph:

```java
public Set<Class<? extends Enum<? extends EnumType>>> scan(final String basePackage) {
  final Set<Class<? extends Enum<? extends EnumType>>> result = new HashSet<>();

  try(
      final ScanResult scanResult = new ClassGraph()
          .enableClassInfo()
          .acceptPackages(basePackage)
          .scan()
  ) {
    for(final Class<?> candidateClass : scanResult.getClassesImplementing(EnumType.class).loadClasses()) {
      if(!candidateClass.isEnum()) {
        throw new RuntimeException("Class is not an enum: " + candidateClass.getName());
      }

      result.add((Class<? extends Enum<? extends EnumType>>)candidateClass);
    }
  }

  return result;
}
```

Method using Spring:

```java
public Set<Class<? extends Enum<? extends EnumType>>> scan(final String basePackage) {
  final ClassPathScanningCandidateComponentProvider provider = new ClassPathScanningCandidateComponentProvider(false);

  provider.addIncludeFilter(new AssignableTypeFilter(EnumType.class));

  final Set<BeanDefinition> candidates = provider.findCandidateComponents(basePackage);

  final Set<Class<? extends Enum<? extends EnumType>>> result = new HashSet<>();

  for(final BeanDefinition beanDefinition : candidates) {
    final String beanClassName = beanDefinition.getBeanClassName();

    final Class<?> beanClass;

    try {
      beanClass = ClassUtils.forName(beanClassName, null);
    } catch (final ClassNotFoundException e) {
      throw new RuntimeException("Could not load class: " + beanClassName, e);
    }

    if(!beanClass.isEnum()) {
      throw new RuntimeException("Class is not an enum: " + beanClassName);
    }

    result.add((Class<? extends Enum<? extends EnumType>>)beanClass);
  }

  return result;
}
```

**Comment by lukehutch** [comment] 2023-09-29 04:27
Probably because ClassGraph finds a lot more classpath resources than other scanners, so it is scanning a lot more jars. If you manually override the classpath before scanning, and specify only the jar(s) you want to scan, ClassGraph will work much faster. Please report back on whether this closes the gap.

**Comment by oliveryasuna** [comment] 2023-09-29 12:53
@lukehutch How do I limit the scan to my _immediate_ classpath?

What do you mean, "ClassGraph finds a lot more classpath resources than other scanners"? What does ClassGraph scan that Spring's scanner does not?

I should mention that these metrics are from running tests.

We end up building a fat JAR, so ClassGraph should perform better in there, right?

**Comment by lukehutch** [comment] 2023-09-29 18:14
If you're scanning just one jar, then probably ClassGraph will be faster, yes, because it has a highly parallelized jar scanner. Call `.overrideClasspath` with the path to the jar before `.scan`.

However you also need to specify which packages you want to scan, rather than scanning everything within the jar, otherwise ever single classfile will be loaded and parsed. And if all you need is annotation scanning, then only enable annotation scanning, don't enable scanning of all classfile properties, such as method and field scanning, etc...

**Comment by lukehutch** [comment] 2023-10-12 21:41
Hi, any updates?

**Comment by lukehutch** [comment] 2023-10-13 08:09
I'll close this since almost certainly the problem is that you're scanning everything in a very large classpath, rather than just the jars, modules, and/or packages you need. Please comment back here if that doesn't seem to be the case.

**Closed as completed by lukehutch** 2023-10-13 08:08 UTC
