### ISSUE TITLE
NoClassDefFoundError on multiple inner classes with different capitalization

### ISSUE THREAD

**Issue by topi314** [classgraph/classgraph#494] opened 2021-01-18 17:17 UTC
tested on 4.8.98

[scan-logs.txt](https://github.com/classgraph/classgraph/files/5831599/scan-logs.txt)

code to reproduce: https://github.com/KittyBot-Org/KittyBot/tree/83fa3c21836bb28eb67851222b0119233f43c5a1

When you have multiple inner classes with same name  but different capitalization class graph produces a java.lang.NoClassDefFoundError

I guess this behavior is not intended so I'm leaving this here

```
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at de.kittybot.kittybot.modules.CommandsModule.scanCommands(CommandsModule.java:53)
	at de.kittybot.kittybot.modules.CommandsModule.onEnable(CommandsModule.java:45)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at de.kittybot.kittybot.module.Modules.<init>(Modules.java:50)
	at de.kittybot.kittybot.main.KittyBot.<init>(KittyBot.java:28)
	at de.kittybot.kittybot.main.Main.main(Main.java:30)
Caused by: java.lang.NoClassDefFoundError: de/kittybot/kittybot/commands/admin/SettingsCommand$NsfwCommand
	at de.kittybot.kittybot.commands.admin.SettingsCommand.<init>(SettingsCommand.java:27)
	... 11 common frames omitted
Caused by: java.lang.ClassNotFoundException: de.kittybot.kittybot.commands.admin.SettingsCommand$NsfwCommand
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 12 common frames omitted
```

**Comment by lukehutch** [comment] 2021-01-19 06:26
Thanks for the bug report. Can you please create a small minimal testcase that shows the problem without the additional code in your project?

**Comment by lukehutch** [comment] 2021-01-21 18:37
@TopiSenpai it's unlikely to be the case of the inner classes that is the problem here. It may be due to the fact that the inner classes are not actually inner classes, they are static, or something.

I just checked in a unit test that tries to recreate the problem, but the test succeeds. Can you please modify this test until you can recreate the bug? Thanks.

**Comment by lukehutch** [comment] 2021-01-23 13:00
@TopiSenpai I tried compiling your project. You have provided no instructions as to how to compile or run the tests, or even which test fails.

```
$ ./gradlew 

FAILURE: Build failed with an exception.

* Where:
Build file '/home/luke/KittyBot/build.gradle' line: 80

* What went wrong:
A problem occurred evaluating root project 'KittyBot'.
> No such property: KITTYBOT_DB_HOST for class: org.jooq.meta.jaxb.Jdbc

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 426ms
```

**Comment by topi314** [comment] 2021-01-23 13:20
For compiling the project you need to remove .example the gradle.properties
Anyway I will have a look at it now!

**Comment by topi314** [comment] 2021-01-23 13:32
I'm just pasting class A here:
```java
/**
 * The Class A.
 */
public class A {
	/**
	 * The Class B.
	 */
    public static class B {
    }

	/**
	 * The Class b.
	 */
	public static class b {
	}
}
and again the logs:
```

```
java.lang.IllegalArgumentException: Could not load class io.github.classgraph.issues.issue494.A$B : java.lang.NoClassDefFoundError: io/github/classgraph/issues/issue494/A$b (wrong name: io/github/classgraph/issues/issue494/A$B)
	at io.github.classgraph.ScanResult.loadClass(ScanResult.java:1219)
	at io.github.classgraph.ScanResultObject.loadClass(ScanResultObject.java:220)
	at io.github.classgraph.ClassInfo.loadClass(ClassInfo.java:2816)
	at io.github.classgraph.issues.issue494.Issue494Test.testStaticInnerClass(Issue494Test.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.NoClassDefFoundError: io/github/classgraph/issues/issue494/A$b (wrong name: io/github/classgraph/issues/issue494/A$B)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1095)
	at io.github.classgraph.ClassGraphClassLoader.findClass(ClassGraphClassLoader.java:249)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:468)
	at io.github.classgraph.ScanResult.loadClass(ScanResult.java:1214)
	... 68 more
```

**Comment by lukehutch** [comment] 2021-01-23 14:33
Oh wow, let me guess, you're using Windows? Or something else, with a case-insensitive filesystem?

The "wrong name" thing means that the classfile for `b` is being found when the classfile for `B` is being requested. Since there's nothing in my code (that I'm aware of) that ever changes the case of filenames or URLs, I don't have any idea how this could happen, other than through an interaction with the filesystem.

The test passes on Linux, even with your new inner class `b` added. I'll see if I can run Windows in a VM to debug this.

**Comment by topi314** [comment] 2021-01-23 14:40
yes I indeed run windows
I noticed this only by accident but that's super interesting
gl with that!

**Comment by lukehutch** [comment] 2021-01-23 14:54
This just got more interesting -- Eclipse on Windows won't even compile class `A` with inner classes `B` and `b`: it gives this error:

```
Class file collision: A resource exists with a different case: '/classgraph/target/test-classes/io/github/classgraph/issues/issue494/A$b.class'.
```

See here:

https://stackoverflow.com/questions/25810791/java-case-sensitivity-class-file-collision-a-resource-exists-with-a-different

So what's happening is:

* The test asks for `A$B`
* The JDK classloader finds the first file with that name on the (case sensitive) filesystem, which happens to be `A$b`
* The classloader compares the name stored in the classfile to the filename, and reports "wrong name"

There are only two ways to fix this, I think:

1. Cross your fingers that there's a way to make the JDK classloader use the case-correct file, if there are multiple files with the same name (I don't know if this is even possible);
2. Hack the `ClassGraphClassLoader` for this special case, so if `NoClassDefFoundError` is thrown, and the error message contains "wrong name", then fall through to loading the bytecodes manually, and defining the class manually. However, probably/possibly accessing resources from URLs or URIs in Java suffers from the same exact confusion, sometimes loading the wrong file.

This is a horrendous Java "bug", if so. Failing to try a case-sensitive match before a case-insensitive match is just plain stupid.

**Comment by lukehutch** [comment] 2021-01-23 14:58
You can make NTFS folders case sensitive using these tips...

https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/

**Comment by lukehutch** [comment] 2021-01-23 15:01
There's more discussion here... this doesn't look promising

https://stackoverflow.com/questions/10890805/case-sensitivity-of-java-class-names

**Comment by lukehutch** [comment] 2021-01-23 15:47
OK, so the failure is happening as follows:

1. `ClassGraphClassLoader` defers to `AppClassLoader` (in JDK>9). This tries to load `B`, gets `b` from the filesystem, and fails.
2. `ClassGraphClassLoader` falls through to loading the `B.class` directly from the disk, is given `b.class` by the filesystem, and then tries to call `defineClass` to define a class, which fails for the same reason.

It would be possible to fix "2." by catching this failure, then getting the directory that contains the classfile, iterating through all the files in that directory, and then finding a case-sensitive match. However, *this would end up allowing ClassGraph to load classfiles when the JDK can't even load them*.

I have tried to make the ClassGraph classloader mimic the JDK classloader (or the environment classloader) as exactly as possible, so that there are no surprises. Therefore, I really should not implement any behavior into ClassGraph that is semantically very different than what the JDK does -- and therefore, unfortunately or not, this is already working as intended, and there is nothing to fix here.

I added a warning, so that the `LinkageError` that you get in this case at least explains the problem: that it's not valid on Windows to have two classfiles of the same name in the same case-insensitive directory, so your code is not portable. This is the best that can be done, I think.

The moral of the story is:

* Classfiles are stored on filesystems
* Filesystems are case-insensitive on Windows
* Therefore, if you want your code to work portably across all operating systems, you should never have two classes with different capitalizations in the same directory. (Hence Eclipse refusing to even compile this code on Windows.)

Sorry that the answer was not better! Thanks for the report.

**Closed as completed by lukehutch** 2021-01-23 15:47 UTC

**Comment by topi314** [comment] 2021-01-23 16:36
alright ty for your time
for me this is no problem as I had 2 sub classes with a capital difference just by accident!
