### ISSUE TITLE
FD leak causes invalid ScanResults when run on large classpath

### ISSUE THREAD

**Issue by johnou** [classgraph/classgraph#223] opened 2018-08-01 11:05 UTC
After upgrading Atomix to ClassGraph i'm seeing that it fails to load public inner classes yet I haven't changed anything wrt class loaders..

```java
java.lang.IllegalArgumentException: Could not load class io.atomix.protocols.backup.MultiPrimaryProtocol$Type

	at io.github.classgraph.ScanResult.loadClass(ScanResult.java:720)
	at io.github.classgraph.ScanResultObject.loadClass(ScanResultObject.java:145)
	at io.github.classgraph.ClassInfo.loadClass(ClassInfo.java:1691)
	at io.atomix.core.impl.ClasspathScanningAtomixRegistry.lambda$new$0(ClasspathScanningAtomixRegistry.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.atomix.core.impl.ClasspathScanningAtomixRegistry.<init>(ClasspathScanningAtomixRegistry.java:52)
	at io.atomix.core.impl.ClasspathScanningAtomixRegistry.<init>(ClasspathScanningAtomixRegistry.java:41)
	at io.atomix.core.AtomixRegistry.registry(AtomixRegistry.java:49)
	at io.atomix.core.Atomix.builder(Atomix.java:288)
	at io.atomix.core.Atomix.builder(Atomix.java:275)
	at io.atomix.core.AbstractAtomixTest.buildAtomix(AbstractAtomixTest.java:76)
	at io.atomix.core.AbstractAtomixTest.createAtomix(AbstractAtomixTest.java:110)
	at io.atomix.core.AbstractAtomixTest.createAtomix(AbstractAtomixTest.java:103)
	at io.atomix.core.AbstractPrimitiveTest.setupCluster(AbstractPrimitiveTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: No classloader was able to load class io.atomix.protocols.backup.MultiPrimaryProtocol$Type
	at io.github.classgraph.ScanResult.loadClass(ScanResult.java:682)
	at io.github.classgraph.ScanResult.loadClass(ScanResult.java:715)
	... 28 more
```

**Comment by johnou** [comment] 2018-08-01 11:06
Here's the update diff https://github.com/atomix/atomix/compare/classgraph

**Comment by lukehutch** [comment] 2018-08-01 12:29
PS please also try loading the outer class, `io.atomix.protocols.backup.MultiPrimaryProtocol`:

`scanResult.getClassInfo("io.atomix.protocols.backup.MultiPrimaryProtocol").loadClass()`

If that succeeds but the inner class fails, and it really does have to do with `Type` being an inner class, that will be a different bug than if the outer class doesn't load either.

**Comment by lukehutch** [comment] 2018-08-01 12:37
Also, let me know what this returns:

```java
System.out.println(
    scanResult.getClassInfo("io.atomix.protocols.backup.MultiPrimaryProtocol$Type")
        .getClasspathElementURL());
```

And please attach verbose logs, so I can see which classloader was supposed to have loaded that class, and how the classloaders are related.

**Comment by johnou** [comment] 2018-08-01 12:42
@lukehutch this is interesting, I changed the constructor scan code to the following..

```java
  public ClasspathScanningAtomixRegistry(ClassLoader classLoader, Collection<Class<? extends NamedType>> types) {
    final String scanSpec = System.getProperty("io.atomix.scanSpec");
    final ClassGraph classGraph = scanSpec != null ?
            new ClassGraph().enableClassInfo().whitelistPackages(scanSpec).addClassLoader(classLoader) :
            new ClassGraph().enableClassInfo().addClassLoader(classLoader);

    ScanResult scanResult = classGraph.scan();

    try {
      scanResult.getClassInfo("io.atomix.protocols.backup.MultiPrimaryProtocol$Type").loadClass();
      scanResult.getClassInfo("io.atomix.protocols.gossip.AntiEntropyProtocol$Type").loadClass();
      scanResult.getClassInfo("io.atomix.protocols.gossip.CrdtProtocol$Type").loadClass();
      scanResult.getClassInfo("io.atomix.protocols.raft.MultiRaftProtocol$Type").loadClass();

    } catch (Exception e) {
      e.printStackTrace();
    }

    for (Class<? extends NamedType> type : types) {
      Map<String, NamedType> registrations = new ConcurrentHashMap<>();

      scanResult.getClassesImplementing(type.getName()).forEach(classInfo -> {
        if (classInfo.isInterface() || classInfo.isAbstract() || Modifier.isPrivate(classInfo.getModifiers())) {
          return;
        }
        NamedType instance = newInstance(classInfo.loadClass());
        NamedType oldInstance = registrations.put(instance.name(), instance);
        if (oldInstance != null) {
          LOGGER.warn("Found multiple types with name={}, classes=[{}, {}]", instance.name(),
                  oldInstance.getClass().getName(), instance.getClass().getName());
        }
      });
      this.registrations.put(type, registrations);
    }
  }
```

then it blows up later in the getClasses call.. 

```
java.lang.IllegalArgumentException: Class is not an interface: io.atomix.core.profile.Profile$Type

	at io.github.classgraph.ClassInfo.getClassesImplementing(ClassInfo.java:1041)
	at io.github.classgraph.ScanResult.getClassesImplementing(ScanResult.java:513)
	at io.atomix.core.impl.ClasspathScanningAtomixRegistry.<init>(ClasspathScanningAtomixRegistry.java:66)
	at io.atomix.core.impl.ClasspathScanningAtomixRegistry.<init>(ClasspathScanningAtomixRegistry.java:42)
	at io.atomix.core.AtomixRegistry.registry(AtomixRegistry.java:49)
	at io.atomix.core.Atomix.builder(Atomix.java:288)
	at io.atomix.core.Atomix.builder(Atomix.java:275)
	at io.atomix.core.AbstractAtomixTest.buildAtomix(AbstractAtomixTest.java:76)
	at io.atomix.core.AbstractAtomixTest.createAtomix(AbstractAtomixTest.java:110)
	at io.atomix.core.AbstractAtomixTest.createAtomix(AbstractAtomixTest.java:103)
	at io.atomix.core.AbstractPrimitiveTest.setupCluster(AbstractPrimitiveTest.java:84)
```

**Comment by lukehutch** [comment] 2018-08-01 12:50
Well is `io.atomix.core.profile.Profile$Type` an interface? If not, you can't query for which classes implement it.

**Comment by johnou** [comment] 2018-08-01 12:59
I think there is an overlap of names in classNameToClassInfo the class structure is quite convolute, I am trying to create a reproducer but you're also welcome to clone the Atomix classgraph branch if you are feeling adventurous ;)

**Comment by johnou** [comment] 2018-08-01 13:12
![screenshot from 2018-08-01 15-11-35](https://user-images.githubusercontent.com/323497/43523613-44713926-959d-11e8-800d-8b7981403767.png)

**Comment by johnou** [comment] 2018-08-01 13:13
![screenshot from 2018-08-01 15-12-33](https://user-images.githubusercontent.com/323497/43523666-66e01c84-959d-11e8-9dee-b4ae503723a7.png)

**Comment by johnou** [comment] 2018-08-01 14:10
I am seeing too many files option exceptions, I wonder if subsequent invocations of classgraph or even in parallel of a large classpath are causing scans to fail "silently".

**Comment by johnou** [comment] 2018-08-01 19:50
[classgraph.log](https://github.com/classgraph/classgraph/files/2250928/classgraph.log)

**Comment by johnou** [comment] 2018-08-01 19:53
@lukehutch could there be a regression in closing fds? I haven't seen this before with fastclasspathscanner.

**Comment by johnou** [comment] 2018-08-01 19:58
@lukehutch like this like here

```java
final ClasspathOrModulePathEntryToClasspathElementMap classpathElementMap = //
                    new ClasspathOrModulePathEntryToClasspathElementMap(enableRecursiveScanning, scanSpec,
                            nestedJarHandler);
```
it is marked autocloseable but isn't inside a try resource block so will never invoke close and close all ClasspathElements io.github.classgraph.Scanner.ClasspathOrModulePathEntryToClasspathElementMap#close

**Comment by johnou** [comment] 2018-08-01 20:14
just cloned the repo, my previous comment might be moot, looks like intellij decompiled it and the output doesn't match the source 1 to 1.

**Comment by lukehutch** [comment] 2018-08-01 20:53
I updated the testcase for this bug to use an inner interface, rather than an inner class, and it works.

Is it possible the code is compiled or modified using some tool like Lombok?

The too many open files thing is a real problem. Let me look into that.

**Comment by lukehutch** [comment] 2018-08-01 20:54
classpathElementMap is only for the classpath elements (e.g. the root directory of a classpath element, or a jarfile, or a module). It's intentional that those are not closed until the end of the scan. The things that are not being closed are the `Resource` objects discovered within each classpath element.

**Comment by johnou** [comment] 2018-08-01 21:01
Nope no Lombok just IntelliJ decompiling from binary, I clicked attach from Maven Central and it's looking better.

What I am observing is that the first few scans work okay, then the following fail (scan results are broken) because there are too many files open.

I noticed io.github.classgraph.Scanner.ClasspathOrModulePathEntryToClasspathElementMap#close is never invoked which is why I flagged it.

**Comment by johnou** [comment] 2018-08-01 21:11
You can see that in the following picture the classgraph scan has completed yet all the fds are still open..

![screenshot from 2018-08-01 23-09-36](https://user-images.githubusercontent.com/323497/43549108-12bb5ab8-95e0-11e8-9cd9-a46a214cc57e.png)

**Comment by johnou** [comment] 2018-08-01 21:13
io.github.classgraph.Resource#read stinks a bit too, RandomAccessFile never closed?

**Comment by johnou** [comment] 2018-08-01 21:29
Despite not closing the RAF I managed to "clear" the fds by invoking GC after scan is complete which would validate my above comment wrt mappedbytebuffers.

**Comment by lukehutch** [comment] 2018-08-01 21:41
Actually they should have been closed, see `ClasspathElement#parseClassfiles()`, and also `ClasspathElementDir#close()`. That's where the `RandomAccessFile` and `FileChannel` were being closed. You can't close them in `#read()`, because the content of the `ByteBuffer` hasn't been read yet by the caller.

However, I was missing a bunch of close logic. Please try with the code I'm about to push, and let me know if it solves this problem. Then we can go back to figuring out why that inner class wasn't detected as an interface!

**Comment by lukehutch** [comment] 2018-08-01 21:42
(I have my number of fds set very high on my machine, otherwise Chrome bombs when it has a lot of tabs open, so I didn't notice this, even on huge classpaths... good catch)

**Comment by lukehutch** [comment] 2018-08-01 21:51
Argh, this is what I was worried about. Some of the FDs do need to be left open, until later in the scan, so aggressively closing them has caused other issues. This will take more work than I initially thought.

**Comment by johnou** [comment] 2018-08-01 21:54
No problem, I am hoping fixing this also resolves the inner class issue.

**Comment by lukehutch** [comment] 2018-08-01 22:05
OK, please try the version I just pushed. It will hopefully solve the FD leak.

**Comment by lukehutch** [comment] 2018-08-01 22:09
PS there are still some resources left around in the `ScanResult` (e.g. temporary files that were created to extract inner jarfiles will be left in `/tmp`). These will be cleaned up when `ScanResult` is GC`d (using a finalizer, which I know is not bulletproof), or on JVM shutdown, via a finalizer hook. This is necessary for classloading. If you perform a large number of scans, GC will hopefully clean these up as needed, but your GC pauses may be larger than normal. Or you can call `ScanResult#close()` to manually clean these up, but lose classloading in general. None of the FDs should be left open though, if the above push works.

**Comment by lukehutch** [comment] 2018-08-01 22:12
(GC was closing the FDs before, as you observed, because then `Resource#close()` was being called on all resources. You noticed "Resource#read stinks a bit too" :-) -- but actually `Resource` was `AutoCloseable`, and `#close()` was in fact closing both the `FileChannel` and the `RandomAccessFile`. I changed the logic so that resources can be opened and closed multiple times.

**Comment by johnou** [comment] 2018-08-01 22:52
`Resource#read` was a bad copy paste, I was actually trying to reference the anonymous class of Resource inside io.github.classgraph.ClasspathElementDir#newClasspathResource which creates a RAF and does not close it.

**Comment by johnou** [comment] 2018-08-01 22:55
There are two fields there but then local variables with shadow names, I think they should be direct assignments so they are closed when close is invoked?

**Comment by johnou** [comment] 2018-08-01 22:56
```
Index: src/main/java/io/github/classgraph/ClasspathElementDir.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/io/github/classgraph/ClasspathElementDir.java	(date 1533162071000)
+++ src/main/java/io/github/classgraph/ClasspathElementDir.java	(date 1533164090000)
@@ -109,9 +109,8 @@
                             "Resource is already open -- cannot open it again without first calling close()");
                 } else {
                     try {
-                        @SuppressWarnings("resource")
-                        final RandomAccessFile randomAccessFile = new RandomAccessFile(classpathResourceFile, "r");
-                        final FileChannel fileChannel = randomAccessFile.getChannel();
+                        randomAccessFile = new RandomAccessFile(classpathResourceFile, "r");
+                        fileChannel = randomAccessFile.getChannel();
                         final MappedByteBuffer buffer = fileChannel.map(FileChannel.MapMode.READ_ONLY, 0,
                                 fileChannel.size());
                         buffer.load();
```

**Comment by johnou** [comment] 2018-08-01 23:01
@lukehutch with master and the above patch the fd leak is fixed and I no longer see the `java.lang.IllegalArgumentException: Class is not an interface: io.atomix.core.profile.Profile$Type` issue, seems when ClassGraph fails to read information about a class the default ClassInfo is applied (interface == false).

**Comment by lukehutch** [comment] 2018-08-01 23:19
@johnou Great, and yes, you're absolutely right about that. What was happening is that the inner interface class was being referenced somewhere else on the classpath, and since the class itself had not been scanned (because it couldn't be, because all the fds were used up), it was created as a placeholder `ClassInfo` for an "external class" (just as with class references for superclasses that are not in a whitelisted path).

I really appreciate you catching this, and for helping me track down the cause. It was a very serious bug!

**Closed** 2018-08-01 23:18 UTC

**Comment by johnou** [comment] 2018-08-01 23:24
You're most welcome!

**Comment by lukehutch** [comment] 2018-08-01 23:25
Released in 4.0.3.

**Comment by lukehutch** [comment] 2018-08-01 23:43
PS @johnou I should say that I'm impressed at the speed at which you have isolated the cause of this issue and previous issues. The ClassGraph codebase has got to be complex from an external perspective. There are all sorts of layers of abstractions, including work queues and recyclers and singleton wrappers and AutoCloseables within AutoCloseables within AutoCloseables, as well as different Resource implementations for directories, jars and modules. I had often wondered how many people would have enough grit to dig into the code!

**Comment by johnou** [comment] 2018-08-02 00:06
Cheers, comes with experience I think, I've lost count the amount of times I have had to attach Spring / Hibernate sources to our projects to debug problems.. I must also thank you again for being so responsive and thorough.
