### ISSUE TITLE
ModuleRef: calling "rawVersion" + "get" throws if the former returns empty Optional

### ISSUE THREAD

**Issue by zhgzhg** [classgraph/classgraph#249] opened 2018-09-11 21:37 UTC
Greetings,

I am not quite sure whether it is supposed to work in this way, but with ClassGraph 4.1.3+ and on Java9+ in "ModuleRef.java" I am getting "IllegalArgumentException"s due to inability to call "get" method, because of the following code fragment in the constructor:

```
final Object optionalRawVersion = ReflectionUtils.invokeMethod(this.descriptor, "rawVersion",
        /* throwException = */ true);                                                        
if (optionalRawVersion != null) {                                                            
    this.rawVersion = (String) ReflectionUtils.invokeMethod(optionalRawVersion, "get",       
            /* throwException = */ true);                                                    
}                                                                                            

```

The optionalRawVersion is checked for null, but in my case the Optional that's returned is just empty, because the module that I have doesn't have a raw version - [https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleDescriptor.html#rawVersion--](https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleDescriptor.html#rawVersion--).

**Comment by lukehutch** [comment] 2018-09-11 23:00
Thanks @zhgzhg for reporting this, and for tracking down the cause (not easy since the logging was terrible in the case of this exception! -- improved now).

The code needed to call `Optional#isPresent()` before `Optional#get()`.

This is fixed and released in version 4.1.7.

**Closed by lukehutch** 2018-09-11 23:00 UTC
