### ISSUE TITLE
NPEs from scan() on ProxyingInputStream.close()

### ISSUE THREAD

**Issue by ericjs** [classgraph/classgraph#626] opened 2022-01-10 19:48 UTC
Using ClassGraph 4.8.138 and Narcissus 1.0.7, on Java 17 under linux.
Code begins
`ClassGraph.CIRCUMVENT_ENCAPSULATION = CircumventEncapsulationMethod.NARCISSUS;
        ClassGraph classGraph = new ClassGraph();
        //classGraph.enableClassInfo();
        classGraph.enableAllInfo();
        try (ScanResult scanResult = classGraph.scan()) {`
And the scan call throws NPE from numerous threads ClassGraph-worker-XX threads.

I read something about some special handling wrt Tomcat, and I'm using Tomcat 8.5. So my first thought is whether since I'm using such an old version of Tomcat I might be out of the bounds of what you're handling...

I'll turn on verbose and get the logging data.

**Comment by ericjs** [comment] 2022-01-10 19:55
Nevermind, I'm an idiot! My debugger was trapping these, but the scan is actually working.

**Comment by lukehutch** [comment] 2022-01-10 20:21
No problem, but can you please confirm whether there were any issues at all with ClassGraph? For example, even if the problems weren't caused by ClassGraph, if the stacktraces in the logs were not helpful, or if ClassGraph was failing the entire scan when it should just fail scanning some individual files, then maybe ClassGraph needs to improve its error logging and error response.

Also, you're the first user who has mentioned that they're using Narcissus. Why did you need that for your environment?

**Comment by ericjs** [comment] 2022-01-10 22:03
It is in fact working, where "working" consists of the following continuation of the code above
```
ClassInfoList subclasses = scanResult.getSubclasses("com.wrycan.xms.serialization.ExampleGenerator");            
for(ClassInfo sc : subclasses){                
    Class<ExampleGenerator> aClass = sc.loadClass(ExampleGenerator.class);
```
Given that, do you have any use for the logs?

I assumed from your documentation section [Running on JDK 16+](https://github.com/classgraph/classgraph#running-on-jdk-16) that I would need it, but perhaps that was a hasty leap, as I'm not 100% sure about the last 3 bullet points. I assume the old Tomcat I'm using must be using a legacy classloader. No idea about it exposing it's classpath, but would assume the last to be true, though I'm unclear on the meaning of "module" there.

I'll have to try it without and see.

**Comment by ericjs** [comment] 2022-01-10 22:04
FWIW, I found out about ClassGraph via your answer to https://stackoverflow.com/questions/492184/how-do-you-find-all-subclasses-of-a-given-class-in-java

**Comment by ericjs** [comment] 2022-01-10 22:15
Welp, it seems it works fine without Narcissus too! I'm afraid that given the way things have gone in trying to get this task done which lead me to ClassGraph, I'd started just assuming worst. ;^)

BTW I was able to get ClassGraph working and doing what I needed extremely quickly. That's high praise for your project and documentation.

**Comment by lukehutch** [comment] 2022-01-10 22:33
If you're not familiar with Java modules, then you definitely are not using the Java module system, so you do not need Narcissus or JVM-Driver, correct.

I only need the logs if you think the logs are showing an error in ClassGraph, or if the logs are incorrectly reporting the source of the problem. Please let me know.

**Comment by ericjs** [comment] 2022-01-10 22:45
I'm familiar with Java modules in the sense of being aware of there being a new feature I've not got around to using or learning in detail yet. I know I'm not using it, but I don't know whether a given version of Tomcat might use it. But if the fourth bullet point is using the word "module" with that same meaning, I'm not clear it how it could make sense in light of bullet point two needing to be true (using a legacy classloader rather than modules).

**Comment by ericjs** [comment] 2022-01-11 00:07
The NPE I'd caught in the debugger which lead me to post this issue, occurs in the close() method of your class nonapi.io.github.classgraph.utils.ProxyingInputStream. While I don't know that is harming anything, I don't know that it isn't. There is nothing in the log about it even with verbose set, but here is the stack trace from the debugger.

```
"ClassGraph-worker-42"
	at nonapi.io.github.classgraph.utils.ProxyingInputStream.close(ProxyingInputStream.java:198)
	at io.github.classgraph.ClasspathElementModule$1$1.close(ClasspathElementModule.java:212)
	at io.github.classgraph.Resource.close(Resource.java:418)
	at io.github.classgraph.ClasspathElementModule$1.close(ClasspathElementModule.java:267)
	at io.github.classgraph.ClasspathElementModule$1$1.close(ClasspathElementModule.java:216)
	at nonapi.io.github.classgraph.fileslice.reader.ClassfileReader.close(ClassfileReader.java:454)
	at io.github.classgraph.Classfile.<init>(Classfile.java:1955)
	at io.github.classgraph.Scanner$ClassfileScannerWorkUnitProcessor.processWorkUnit(Scanner.java:750)
	at io.github.classgraph.Scanner$ClassfileScannerWorkUnitProcessor.processWorkUnit(Scanner.java:673)
	at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:246)
	at nonapi.io.github.classgraph.concurrency.WorkQueue.access$000(WorkQueue.java:50)
	at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:201)
	at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:198)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by lukehutch** [comment] 2022-01-11 06:11
@ericjs Great, thanks, this was indeed a bug, although it probably didn't affect anything, since I think exceptions in close() are pretty universally ignored. Fixed in https://github.com/classgraph/classgraph/commit/45d5b991aed611abd228efcd2ecd40ba02489f24 .

**Closed as completed by lukehutch** 2022-01-11 06:11 UTC

**Comment by ericjs** [comment] 2022-01-11 17:47
Any thoughts on my comment about the bullet points in https://github.com/classgraph/classgraph#running-on-jdk-16? How can all 4 of them ever be true? If point 2 is true, how can point 4 even apply? Am I misreading something?

**Comment by lukehutch** [comment] 2022-01-11 18:19
Sorry, you're right... I updated the points. Thanks.
