### ISSUE TITLE
Version 4.6 does not cleanup temp files

### ISSUE THREAD

**Issue by torstenkuhnhenne** [classgraph/classgraph#288] opened 2018-12-07 08:30 UTC
After the upgrade from version 4.4.12 to 4.6.3 we have the problem, that sometimes some of the temp files remain in the system temp-folder.

I debuged in the code and found out that in `NestJarHandler#close()` the method `tempFile.delete()` returns false. And on the other hand I have 3 temporary files in my folder and only 1 File object in the `tempFiles` list.

![classgraph](https://user-images.githubusercontent.com/19815499/49635754-0cb68680-fa01-11e8-8ba0-99f80d152c84.png)
![classgraph_2](https://user-images.githubusercontent.com/19815499/49635759-104a0d80-fa01-11e8-8202-79f1abd288c9.png)

As you can see, there a 3 temp files and only one of them was in the internal `tempFiles` list.

Log output (from a different run than seen on the screenshots, but this run also doesn't delete all temp files):
[verbose.log](https://github.com/classgraph/classgraph/files/2656439/verbose.log)

Code:
```
static List<Class<Neo4jBaseObject>> getObjects() throws ClassNotFoundException {
    try ( final ScanResult scanResult = new ClassGraph().verbose().enableAllInfo()
            .whitelistPackages( "de.myview.xom.neo4j.domain" ).scan() ) {
        final ClassInfoList candidates = scanResult.getSubclasses( Neo4jBaseObject.class.getName() );

        final List<Class<Neo4jBaseObject>> testClasses = candidates.stream().filter( classInfo -> !classInfo.isAbstract() )
                .map( classInfo -> classInfo.loadClass( Neo4jBaseObject.class ) ).collect( Collectors.toList() );
        return testClasses;
    }
}
```

Feel free to ask if I can provide further information.

**Comment by lukehutch** [comment] 2018-12-07 09:04
@torstenkuhnhenne Thanks for the detailed report, and interesting -- there have been reports before that temp files are not cleaned up properly on Windows. I wonder if `File::delete` sometimes fails for strange reasons.

It's also interesting that temp files are being created at all. This only happens if a nested jar is deflated, rather than stored, and if its size is larger than 32MB. Is that the case for `aws-java-sdk.1.11.21.jar`?

Are the three temp files you see created from three separate runs? (I'm hoping that the same nested jar is not being extracted twice in the same run, since two of the timestamps are the same down to the minute).

Temp files are marked for deletion on JVM shutdown, so as long as you don't terminate your program early in the Eclipse debugger (since that [causes shutdown hooks not to run](https://bugs.eclipse.org/bugs/show_bug.cgi?id=38016)), the temp files should be deleted on exit. Can you please confirm if the three files you see left over were due to terminating the program in the Eclipse debugger?

I don't have an easy way to test this on Windows (I could spin up a VM, but I don't have any actual Windows machines to test on). Can you please stop the debugger at the same point you have shown, and look at the path in `tempFile`, to make sure it exists? Can you then please look in Windows SysInternals' Process Explorer to see if ClassGraph still has the file open at this point?

It is possible the file delete is failing because the file is still open. On Windows, I believe file deletion will fail when a file is open, whereas on Linux, files can be happily deleted while still open, since the filesystem holds a ref in memory to the inode of the file while a file is open.

If this is the problem, solving this will be difficult, since files are mmap'd to open them, and the only way to un-mmap a file in Java is to garbage collect the `MappedByteBuffer`.

It is possible (but not guaranteed) that inserting a `System.gc()` before the file deletions could solve the problem. If you are able to build ClassGraph from source (just use `mvn package`), and could test inserting this, I would really appreciate it.

`System.gc()` is not even guaranteed to trigger the garbage collector though, so I don't know if there is a proper way to solve this in Java. If the problem is what I think it is, this must have been hit before by other projects on Windows...

**Comment by lukehutch** [comment] 2018-12-07 09:13
Indeed I found a JDK bug about this:

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4715154

So this probably is the source of the problem.

System.gc() is the best hope of fixing this, so I inserted that into the code. Can you please test the git master version?

**Comment by torstenkuhnhenne** [comment] 2018-12-07 10:15
Hi @lukehutch ,
wow, that was a really quick response! And a lot of questions ;-)

Yes, the file `aws-java-sdk-1.11.21.jar` is bigger than 32MB. And it is not necessary to scan this file, so i will exlude the parent archive.

First i thought that all 3 files are generated by one run but now i can say that there is one temp file per run.

And now the most important one: I have testet the master version and now all temp file are removed :-)

Thanks a lot for the quick response and fix! :-)

**Comment by lukehutch** [comment] 2018-12-07 10:30
@torstenkuhnhenne You're welcome, and great, thanks for testing! So you can say with high confidence that files were not being removed before switching to master, and they are being removed after switching to master? If so, I will push out a release.

A few followup questions, just to spot-check a few other things:

What was the parent jar that contains `aws-java-sdk-1.11.21.jar`? Can you please verify that `aws-java-sdk-1.11.21.jar` is deflated in the parent jar, not stored? It is quite unusual for nested jars to be deflated, and extremely rare for nested jars of this size to be deflated. Although it is possible that Amazon never compressed their SDK jar for performance reasons, maybe...

One more question: What do you think is a reasonable uncompressed size threshold to spill over to temporary files, vs. holding an unzipped nested jar in RAM? (Yes, this is a subjective question, and the total impact on RAM depends not just on the threshold, but also on the number of nested deflated jars extracted to RAM.) I picked 32MB arbitrarily, thinking the vast majority of jars shouldn't be this big, so I'm quite surprised the AWS SDK jar is larger than that threshold...

**Comment by lukehutch** [comment] 2018-12-07 10:33
Also, just to double-triple check, and sorry for the dumb question, but can you please verify that temp files are now removed *without* excluding the parent archive of the AWS jar? (I only mention this because you said you were going to exclude the parent jar, then said the temp files are all now magically removed... I have to ask the obvious question!)

**Comment by lukehutch** [comment] 2018-12-07 10:38
(I figured it couldn't hurt to push this out as a release either way, so I just released 4.6.4, but I'm still curious to hear your responses to my other questions -- sorry for so many questions!)

**Comment by torstenkuhnhenne** [comment] 2018-12-07 10:44
@lukehutch Yes, for my tests all temporary files are removed now.

The parent-jar for is an interal jar with an "installable" 3rd party software. So this jar is quite big (~100MB) but we have do this trick so that we can download and install the software in our integration tests.

I double-checked it again and with the master version the aws-jar is created in my temp folder and then deleted.

Good question ... in my project the largest jar file has 12MB. I think that 32MB is a good choice and I agree that most archives are very small.

**Comment by lukehutch** [comment] 2018-12-07 10:49
@torstenkuhnhenne thanks for verifying, and thanks for your answers. Can you please also verify that `aws-java-sdk-1.11.21.jar` is deflated, not stored, in the parent jarfile? You can see the compression method in any desktop zip tool, or using `less` on Linux.

I just want to make sure that I'm not wrongly extracting nested jarfiles to disk if they're stored rather than deflated. (Stored nested jars should never be extracted to RAM or disk, they can just be read in-place using a "slice" or byte range of the parent zipfile.)

**Comment by lukehutch** [comment] 2018-12-07 11:02
I just realized I made a lifecycle error in 4.6.4, so you'll want 4.6.5 instead (4.6.5 allows multiple `ScanResult` instances to exist at once, and be closed separately).

**Comment by torstenkuhnhenne** [comment] 2018-12-07 11:15
@lukehutch I can confirm that `aws-java-sdk-1.11.21.jar` is `deflated` in the parent jar.

**Comment by lukehutch** [comment] 2018-12-07 11:17
@torstenkuhnhenne Great, thanks again. Closing!

**Closed by lukehutch** 2018-12-07 11:17 UTC
