### ISSUE TITLE
Fast Classpath Scanner 2.18.1

### ISSUE THREAD

**Issue by ocean927** [classgraph/classgraph#248] opened 2018-09-10 13:11 UTC
Hi,

This is not a bug. I want my scanner pick up all locations of class bytecode. In every case, ScanResult.getClassLoaderForClass() or an altenative ClassInfo.getClasspathElementsURI returns a single value. 

In reality, the class may reside (duped) in many jars and I want to find those URLs and report on them. Is there way to do this via options?

Thanks

**Comment by lukehutch** [comment] 2018-09-10 13:40
Firstly, you are using a very old version, you should port your code from FastClasspathScanner to ClassGraph (which is the new name for FastClasspathScanner version 4). There have been countless bugs fixed, and support for many more classpath mechanisms added since the version you are using. 

You can find locations of duplicated classes by searching for resource files with the name of the class (since resources are not deduplicated the way classes are). For example, for class `x.y.Z`, search for file `x/y/Z.class`. In ClassGraph, you use the `Resource` API for that (and you can get a URL from a `Resource`). (In FastClasspathScanner, you had to use a `FileMatchProcessor`.)

At one point in a version of FastClasspathScanner (I forget which version, but maybe 18 months ago), resource files were deduplicated just like classfiles, so if the above situation doesn't work, you will need to upgrade your library version. If you are going to do that, you may as well also switch to the ClassGraph API.

Hope this helps!

**Comment by lukehutch** [comment] 2018-09-10 13:41
I'll close this since its not a bug, but feel free to keep adding comments.

**Closed by lukehutch** 2018-09-10 13:41 UTC
