### ISSUE TITLE
An error occurs when calling io.github.classgraph.Scanner.performScan().

### ISSUE THREAD

**Issue by ahamana** [classgraph/classgraph#347] opened 2019-05-13 12:02 UTC
After upgrading from 4.8.33 to 4.8.34, an error occurs when calling io.github.classgraph.Scanner.performScan().

The statcktrace is as follows.
```
Caused by: io.github.classgraph.ClassGraphException: Uncaught exception during scan
	at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1183)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1201)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1214)
	at jp.co.nextcolors.framework.bean.util.BeanConverterUtil.registerConverters(BeanConverterUtil.java:49)
	at jp.co.nextcolors.koinomi.listener.ApplicationContextListener.contextInitialized(ApplicationContextListener.java:33)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5156)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:682)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5725)
	... 48 more
Caused by: java.lang.IllegalArgumentException: Class META-INF.versions.9.module-info should not have been scheduled more than once for scanning due to classpath masking -- please report this bug at: https://github.com/classgraph/classgraph/issues
	at io.github.classgraph.Scanner.performScan(Scanner.java:817)
	at io.github.classgraph.Scanner.openClasspathElementsThenScan(Scanner.java:971)
	at io.github.classgraph.Scanner.call(Scanner.java:1006)
	at io.github.classgraph.Scanner.call(Scanner.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by lukehutch** [comment] 2019-05-14 05:41
@ahamana Thanks, this may be some sort of race condition, can you trigger it reliably? If so, are you able to share a minimum reproducing project with me please?

**Comment by ahamana** [comment] 2019-05-14 05:52
@lukehutch Maybe, this cause is on module-info of OSS libraries used on my application.
I will try to create a project for reproducing this issue this weekend.

**Comment by lukehutch** [comment] 2019-05-14 05:54
@ahamana Thank you. I saw this during testing, but I thought I fixed it before the release, and I can't reproduce it now.

**Comment by lukehutch** [comment] 2019-05-14 07:54
> I will try to create a project for reproducing this issue this weekend.

@ahamana Actually no need, I found and fixed this. I will push out a release soon.

**Comment by lukehutch** [comment] 2019-05-14 08:15
@ahamana Fixed and released in 4.8.35. Thank you!

**Comment by lukehutch** [comment] 2019-05-14 08:23
For the record, there were three interacting issues here: 

* An `IllegalArgumentException` was being thrown if two different classpath elements contained a `package-info.class` or a `module-info.class` file for the same package. (This was the recent regression.)
* `module-info.class` was accepted at any location other than the package root (which is the only place it is valid) -- so in your case, it was being found at `META-INF/versions/9/module-info.class`, and read, whereas it should have been ignored.
* More specifically, some jars have multirelease sections (with a path starting `META-INF/versions/{versionNum}/`, but they are missing the `Multi-Release: true` key in their manifest file, so they are technically not actually multi-release jars, and everything inside `META-INF/versions/` should be ignored.

This is all fixed in 4.8.35.

**Closed by lukehutch** 2019-05-14 08:23 UTC

**Comment by ahamana** [comment] 2019-05-14 23:21
@lukehutch The latest version in Maven is still 4.8.34. I will test after it is updated to 4.8.35 in Maven. Thank you so much for your quick action.

**Comment by lukehutch** [comment] 2019-05-14 23:53
> @lukehutch The latest version in Maven is still 4.8.34. I will test after it is updated to 4.8.35 in Maven.

@ahamana You're right, there was a transient failure on Sonatype. I just pushed the release again. You should be able to get the jar from Sonatype now, or it usually takes an hour or two to sync to Maven Central.

> Thank you so much for your quick action.

You're welcome. I just published this a couple of days ago...

https://github.com/classgraph/classgraph/blob/master/Zero-Bugs-Commitment.md

**Comment by ahamana** [comment] 2019-05-15 09:55
@lukehutch The version 4.8.35 works fine! Thank you.

**Comment by lukehutch** [comment] 2019-05-15 14:54
Great, thanks for confirming!
