### ISSUE TITLE
Scan not performed on saved ClassGraph object

### ISSUE THREAD

**Issue by CDPrete** [classgraph/classgraph#398] opened 2020-02-04 10:47 UTC
Hi.
I don't understand why the scanning is not performed if I store the ClassGraph instance in a variable before calling the `scan()` method.

For example:
```
class MyMavenRunner{
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            val parsedArgs = parseCommandArgs(args)
            val classGraph =
                    ClassGraph()
                            .verbose()
                            .enableClassInfo()
                            .enableMethodInfo()
                            .disableJarScanning()
                            .disableNestedJarScanning()
                            .whitelistPackages(BASE_PACKAGE)
                            .overrideClasspath(parsedArgs.projectBuildPath.toString())

            val data= generateData(classGraph)
            print(data)
        }
    }
}
```
(where `generateData(ClassGraph)`, declared in another class as `static`, calls inside `classGraph.scan().use {...}`) doesn't work (I get **2020-02-04T11:35:35.667+0100    ClassGraph      Only returning classpath elements (not performing a scan)** from the `verbose()`, which causes then an NPE when I call `getClassesImplementing(MyClass.class.canonicalName)`), but if I do
```
ClassGraph()
                            .verbose()
                            .enableClassInfo()
                            .enableMethodInfo()
                            .disableJarScanning()
                            .disableNestedJarScanning()
                            .whitelistPackages(BASE_PACKAGE)
                            .overrideClasspath(parsedArgs.projectBuildPath.toString())
                            .scan()
                            .use { scanResult -> ... }
```
inside the `generateData` directly it works fine.

The `main(args)` is called from the Maven Exec Plugin.

**Comment by lukehutch** [comment] 2020-02-04 14:19
Can you please produce a small standalone project that reproduces this behavior, so I can take a look?

**Comment by lukehutch** [comment] 2020-02-04 14:24
Most likely you're calling `classGraph.getClasspathURIs()` or similar on the saved instance before your try to call `.scan()`. You can only do one of these two things (since getting the path actually runs a partial scan), hence the error message you're seeing. (But actually that's a restriction I should probably lift...)

**Comment by CDPrete** [comment] 2020-02-04 14:43
> Most likely you're calling `classGraph.getClasspathURIs()` or similar on the saved instance before you try to call `.scan()`. You can only do one of these two things (since getting the path actually runs a partial scan), hence the error message you're seeing. (But actually that's a restriction I should probably lift...)

Before the `scan()` I'm actually calling the `getClasspath()` for logging purposes.

What is really weird is that, if I declare the instance in a `static` variable in the main class and reference it through such class (explicitly with `MyMavenRunner.classGraph` in the other classes it works.
If I try to pass the exact same `static` variable as argument to the other methods of the other classes it fails with the same error.

**Comment by CDPrete** [comment] 2020-02-04 15:40
Moving the `getClasspath()` inside the `use{ }` fixed the issue, but now I've another one which affects just Kotlin sources (I was not able to reproduce it with Javas).
Let me know if I should open another issue or if you want to continue here

**Comment by CDPrete** [comment] 2020-02-04 15:47
Moving the `getClasspath()` inside the `use{ }` fixed the issue, but now I've another one which affects just Kotlin sources (I was not able to reproduce it with Javas).
Let me know if I should open another issue or if you want to continue here

**Comment by lukehutch** [comment] 2020-02-04 16:07
Hi, please try the git master version, it should fix the issue.

If you found a separate problem, please open a new bug for that. Thanks!

**Comment by lukehutch** [comment] 2020-02-05 02:57
For reference:

> Moving the `getClasspath()` inside the `use{ }` fixed the issue

This means you're calling `ScanResult.getClasspath()`, rather than `ClassGraph.getClasspath()`, which is a very different code path.

The latest checkin should resolve the problem you originally ran into though, so I just pushed out version 4.8.61. I'll close this bug, but please open a new bug for the other issue you alluded to, if it's still present.

**Closed by lukehutch** 2020-02-05 02:57 UTC

**Comment by CDPrete** [comment] 2020-02-05 16:21
> For reference:
> 
> > Moving the `getClasspath()` inside the `use{ }` fixed the issue
> 
> This means you're calling `ScanResult.getClasspath()`, rather than `ClassGraph.getClasspath()`, which is a very different code path.

Not really. I was calling it on the `classGraph` input variable (also because I was printing it before calling the `scan().use{...}`)

**Comment by lukehutch** [comment] 2020-02-05 18:04
Makes sense, I thought you were using it with `it` in `use { ... }`.

Please let me know if the fix worked for you (it should do).

**Comment by CDPrete** [comment] 2020-02-05 19:11
> For reference:
> 
> but please open a new bug for the other issue you alluded to, if it's still present.

It's this one: https://github.com/classgraph/classgraph/issues/399
