### ISSUE TITLE
Include superclass fields in ScanResult

### ISSUE THREAD

**Issue by reitzmichnicht** [classgraph/classgraph#350] opened 2019-06-04 20:15 UTC
I'm a really happy user of this library, but stumpled upon a missing feature.

When calling .getClassesWithFieldAnnotation(String className) on the ScanResult it will only look at the declared fields of the class itself, not on any fields of the upper hierarchy.

I know this is the default java reflection behavior, but it would be either great to have an additional option to include upperclasses, or to change the default behavior because in my opinion a class should always be treated including all inherited stuff.

Kind regards,
Michael

**Comment by lukehutch** [comment] 2019-06-05 05:06
Hi @reitzmichnicht,

This is a good suggestion. I modified most methods to work with class inheritance many months ago, and added `.getDeclared...()` versions for when you want only matches in the class itself, but I missed this  `getClassesWithFieldAnnotation` method, and also  `getClassesWithMethodAnnotation`. 

It would actually be a simple fix: before these methods return, if the field or method is not private, and the class is not final, add into the result list all subclasses of the class. (Then also create a `.getDeclared...()` version that does not do this.)

Want to take a shot at it?

**Comment by lukehutch** [comment] 2019-06-05 07:17
Actually it's not quite as straightforward as I originally thought, so I went ahead and implemented a prototype. Can you please test the git master version and let me know if it works for you? Thanks.

**Comment by reitzmichnicht** [comment] 2019-06-05 08:50
Yes I already had a look and did not find an easy point for extension.
I tried your snapshot version, but I realized that it doesn't help for my case:

```
public class IdEntity {
  @Id
  @Column(updatable = false)
  @GeneratedValue
  private Long id;
}

public class FooEntity extends IdEntity {
  ...
}

  private static Stream<? extends Class<?>> findGeneratedEntities() {
    return new ClassGraph()
        .whitelistPackages(EntityTest.class.getPackage().getName())
        .enableFieldInfo()
        .enableAnnotationInfo()
        .ignoreFieldVisibility()
        .scan()
        .getClassesWithFieldAnnotation(GeneratedValue.class.getName())
        .filter(x -> !x.isAnonymousInnerClass() && !x.isAbstract() && x.isPublic())
        .loadClasses()
        .stream();
  }
```

If I look at your commit I expect that you do not consider private fields of superclasses which is normally correct. Is it reasonable to consider them when the ignoreFieldVisibility() option is set?

**Comment by lukehutch** [comment] 2019-06-05 18:47
At first I was thinking, "There is no way for `FooEntity` to access the private field `id`, so I don't actually see how this would be useful", but I guess subclasses can inherit the behavior of superclass with annotations on fields/methods, even if they don't inherit the fields/methods themselves. So I guess respecting `ignoreFieldVisibility()` might make sense here? I'm on the fence about it, although I see the utility for the (fairly common) example you gave. 

I'm curious though -- I think you can't even get the value of private fields in superclass es using reflection, without manually walking up the superclass hierarchy? How is this field used to persist the object?

**Comment by reitzmichnicht** [comment] 2019-06-05 19:48
I was also thinking about it. For my example this is all about beans, entities and the javaee reflection magic stuff. As all private fields have public getters and setters its not needed to make the fields itself visible to subclasses.

In general I think as field annotations are always retrieved by reflection, it makes totally sense to ignore the modifiers for this case.

**Comment by lukehutch** [comment] 2019-06-05 20:52
Right, for this case.. But I'm wondering if it's right to do this for the general case. With the change you're suggesting, there will be classes returned that won't have a method or field with the requested annotation. That doesn't seem right as the default behavior...

**Comment by reitzmichnicht** [comment] 2019-06-06 07:24
I found a good solution that works pretty good with master implementation:
```
private static ClassInfoList findGeneratedEntities() {
    ClassInfoList generated = new ClassGraph()
        .whitelistPackages(EntityTest.class.getPackage().getName())
        .enableFieldInfo()
        .enableAnnotationInfo()
        .ignoreFieldVisibility()
        .scan()
        .getClassesWithFieldAnnotation(GeneratedValue.class.getName());
    return generated.stream()
                    .map(ClassInfo::getSubclasses)
                    .reduce(generated, ClassInfoList::union);
```
So I'm with you to not change the default behavior.

**Comment by lukehutch** [comment] 2019-06-06 08:29
That's the suggestion I was going to make :) However, be aware that using `union` the way that you are will incur O(N^2) penalty. It's better to use `Set::add` to merge all the results together.

Can you please test the latest patch for cases where the field of method is non-private (and therefore inherited)? If you have a chance, writing a quick unit test for this would help. If you don't have time, I can write it.

**Comment by lukehutch** [comment] 2019-06-07 08:47
@reitzmichnicht I wrote a unit test, and the change seems to be working as intended, so I pushed this out as version 4.8.38. Thanks for the suggestion!

By the way, in addition to the change I suggested to your code (to avoid O(N^2) scaling complexity), you should always assign the `ScanResult` in a try-with-resources block, so that any associated resources are closed as soon as you no longer need them. So your example should look like this (which will cause the function to return `Set<ClassInfo>` rather than `ClassInfoList`):

```java
        try (ScanResult scanResult = new ClassGraph()
                .whitelistPackages(EntityTest.class.getPackage().getName())
                .enableFieldInfo()
                .enableAnnotationInfo()
                .ignoreFieldVisibility()
                .scan()) {
            final Set<ClassInfo> classInfoSet = new HashSet<>();
            scanResult.getClassesWithFieldAnnotation(GeneratedValue.class.getName())
                    .stream()
                    .map(ClassInfo::getSubclasses)
                    .forEach(classInfoSet::addAll);
            return classInfoSet;
        }
```

**Closed by lukehutch** 2019-06-07 08:47 UTC

**Comment by reitzmichnicht** [comment] 2019-06-07 20:00
Thanks a lot. You are too fast for me :)
Never scrolled down to the bottom of the ScanResult Wiki, thanks for the hint. But in this case I want to return ClassInfoList, so closing it before would be bad. This also prevents me from using HashSet because I cannot create a ClassInfoList myself again.

**Comment by lukehutch** [comment] 2019-06-08 03:33
Thanks, I added a code example at the top of the `ScanResult` wiki page, so that the need to close it is more obvious...

If you don't close `ScanResult`, the garbage collector will close it at some random time. But be aware that if you return a `ClassInfoList` (or `Set<ClassInfo>`), and the `ScanResult` is closed at any point, arbitrary things can break if you try to use the `ClassInfo` objects that are returned. (In particular, classloading via `ClassInfo#loadClass()` will fail.) So if there's any way to tie the lifecycle of the `ScanResult` to the timespan over which you need to use the `ClassInfo` objects (even just running the scan on startup, and holding a reference to the `ScanResult`), you should do that.

The alternative, if you just want to use the environment classloader for classloading, is to extract any information you need from the `ClassInfo` objects (e.g. names of classes that match your criteria), then return that list instead of the collection of `ClassInfo` objects.

**Comment by lukehutch** [comment] 2019-06-10 09:56
Should I expose the `ClassInfoList` constructor? Do you need it?

**Comment by reitzmichnicht** [comment] 2019-06-12 08:36
See https://github.com/classgraph/classgraph/pull/351

**Comment by lukehutch** [comment] 2019-06-12 10:14
The `ClassInfo` constructors are now exposed publicly in 4.8.39.
