### ISSUE TITLE
Scans classes which do not exist anymore

### ISSUE THREAD

**Issue by PXAV** [classgraph/classgraph#392] opened 2019-12-22 09:22 UTC
I have written a simplified util for scanning methods, which looks like this:
```java
filter(new String[] {"abc.yx"}, // packages
            MethodCriterion.annotatedWith(Deprecated.class), // criteria
            MethodCriterion.hasParameters(0))
            
            .forEach(current -> {
              System.out.println("Found Method:");
              System.out.println(current.getName());
            });
```

In the background, this filter method uses class graph:
```java
public Stream<Method> filter(String[] packageNames, MethodCriterion... methodCriteria) {

    Collection<Method> output = Lists.newArrayList();

    try (ScanResult scanResult = new ClassGraph()
            .enableAllInfo()
            .whitelistPackages(packageNames)
            .verbose()
            .scan()) {

      ClassInfoList allClasses = scanResult.getAllClasses();

      for (ClassInfo current : allClasses) {
        System.out.println("scanning class " + current);
        MethodInfoList methodInfos = current.getMethodInfo();
        for (MethodInfo methodInfo : methodInfos) {
          Method method = methodInfo.loadClassAndGetMethod();
          for (MethodCriterion methodCriterion : methodCriteria) {
            if (methodCriterion.matches(method) && !output.contains(method)) {
              output.add(method);
            }
          }
        }
      }
    }

    return output.stream().filter(Objects::nonNull);
  }
```

But when scanning the classes, class graph does also list classes which have already been deleted and do not exist anymore. Therefore it throws an exception when loading the class/method using `methodInfo#loadClassAndGetMethod()`
```
[10:02:45 ERROR]: Error occurred while enabling Kelp v0.1-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: No such method: de.pxav.kelp.core.inventory.item.NbtTag.setKey
	at io.github.classgraph.MethodInfo.loadClassAndGetMethod(MethodInfo.java:596) ~[?:?]
	at de.pxav.kelp.core.reflect.MethodFinder.filter(MethodFinder.java:50) ~[?:?]
	at de.pxav.kelp.core.listener.EventRegistration.initialize(EventRegistration.java:41) ~[?:?]
	at de.pxav.kelp.core.KelpPlugin.onEnable(KelpPlugin.java:103) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

The verbose log: https://hasteb.in/cayeqewi.yaml

Why does class graph still notice classes which have already been deleted? Is this a bug or do I have to refresh something in the classpath?

**Comment by lukehutch** [comment] 2019-12-22 10:16
How exactly are you deleting classes, and why? After you delete classes, do you see in the verbose log (comparing the log for a scan before and after deleting a classfile) that ClassGraph no longer finds the class in question? `scanResult.getAllClasses()` still finds a class, yes, but you will need to directly compare the logs for scanning before and after deleting a classfile to see where it's still finding the class. It's possible that you have the class in two locations on the classpath.

The `loadClass()` method inside `MethodInfo.loadClassAndGetMethod` is still succeeding, so the class is actually found -- but it doesn't have a method of the expected name. This may indicate that not only do you have two copies of the class on the classpath, but they're different (one copy doesn't have the expected method).

You can check this by manually calling `current.loadClass()` (which is called within the `MethodInfo.loadClassAndGetMethod` method before trying to get the `Method` reference for the named method from the `Class<?>` reference), and then you can check which methods it has (using standard reflection methods).

One thing to be aware of is that if any class has ever been loaded, e.g. by any reference to it being resolved from any other class that was loaded and initialized, then it will be cached in the classloader or its parent. That means even if you physically delete the class from the classpath, the class will still be loaded. [Getting around this is possible but very tricky.](https://stackoverflow.com/a/148762/3950982)

By the way there are a couple of issues with your code:

1. Your innermost `for` loop has time complexity O(N^2), since the `!output.contains(method)` test is O(N). You should use a `Set<Method>`, not a `List<Method>`, for `output`, and then remove the `!output.contains(method)` test (you don't need it anymore). Then the time complexity will be O(N).
2. The way you implemented the `methodCriterion` loop, you have implemented Boolean OR logic. You probably want Boolean AND, by the looks of it (when multiple criteria are specified). You need to make sure that `methodCriterion.matches(method)` is true for all criteria, not just for the first one that matches.

**Comment by PXAV** [comment] 2019-12-22 11:29
> How exactly are you deleting classes, and why?

I deleted some classes which are no longer needed because they were used for debugging reasons or have been replaced by better solutions. Since the code isn't used anywhere in production yet, this is not a problem. I delete classes by simply clicking the delete button in my IDE.


> After you delete classes, do you see in the verbose log (comparing the log for a scan before and after deleting a classfile) that ClassGraph no longer finds the class in question?

To find that out, I've created a `TestClass` with some example code and generated a verbose log (https://hasteb.in/qipeqoku.yaml), which displays the expected result:
```
2019-12-22T12:03:48.415+0100	ClassGraph	---- Found classfile within subpackage of whitelisted package: de/pxav/kelp/core/reflect/TestClass.class
2019-12-22T12:03:48.460+0100	ClassGraph	------ Parsing classfile (took 0.000137 sec)
2019-12-22T12:03:48.461+0100	ClassGraph	-------- Found class de.pxav.kelp.core.reflect.TestClass
2019-12-22T12:03:48.461+0100	ClassGraph	---------- Superclass: java.lang.Object
2019-12-22T12:03:48.461+0100	ClassGraph	---------- Field: private int anAttribute
2019-12-22T12:03:48.461+0100	ClassGraph	---------- Method: public <init>()
2019-12-22T12:03:48.461+0100	ClassGraph	---------- Method: private void aMethod()
```
After that, I deleted the class, recompiled the `jar` file and got the following log (https://hasteb.in/owimecoh.yaml):
```
2019-12-22T12:09:06.324+0100	ClassGraph	---- Found classfile within subpackage of whitelisted package: de/pxav/kelp/core/reflect/TestClass.class
2019-12-22T12:09:06.370+0100	ClassGraph	------ Parsing classfile (took 0.000128 sec)
2019-12-22T12:09:06.370+0100	ClassGraph	-------- Found class de.pxav.kelp.core.reflect.TestClass
2019-12-22T12:09:06.370+0100	ClassGraph	---------- Superclass: java.lang.Object
2019-12-22T12:09:06.370+0100	ClassGraph	---------- Field: private int anAttribute
2019-12-22T12:09:06.370+0100	ClassGraph	---------- Method: public <init>()
2019-12-22T12:09:06.370+0100	ClassGraph	---------- Method: private void aMethod()
```
So the class still seems to exist in the class path. When I looked in the jar file (using default archive manager) the `.class` file still appeared in its package, which would mean the IDE (IntelliJ IDEA) has not deleted the class correctly.

But the class from the fist command (`NbtTag`) does not appear as `.class` file in the package, but is still loaded by ClassGraph as you can see in all the log files:
```
2019-12-22T12:09:06.324+0100	ClassGraph	---- Found classfile within subpackage of whitelisted package: de/pxav/kelp/core/inventory/item/NbtTag.class
2019-12-22T12:09:06.375+0100	ClassGraph	------ Parsing classfile (took 0.000486 sec)
2019-12-22T12:09:06.375+0100	ClassGraph	-------- Found class de.pxav.kelp.core.inventory.item.NbtTag
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Superclass: java.lang.Object
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Field: public K key
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Field: public V value
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Method: public <init>(K, V)
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Method: public void setKey(K)
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Method: public void setValue(V)
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Method: public K getKey()
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Method: public V getValue()
2019-12-22T12:09:06.375+0100	ClassGraph	---------- Class type signature: public class de.pxav.kelp.core.inventory.item.NbtTag<K, V>
```
And as you can see as well it loads the `#setKey(K)` method, which does no longer exist according to the error message from my first post.

> This may indicate that not only do you have two copies of the class on the classpath, but they're different (one copy doesn't have the expected method).

I don't think this is the case, because it appears only one time in the log.

> You can check this by manually calling `current.loadClass()`

I did this and logged all methods of the class. Output:
```
[12:09:06 INFO]: ==> method: getKey
[12:09:06 INFO]: ==> method: setValue
[12:09:06 INFO]: ==> method: wait
[12:09:06 INFO]: ==> method: wait
[12:09:06 INFO]: ==> method: wait
[12:09:06 INFO]: ==> method: equals
[12:09:06 INFO]: ==> method: toString
[12:09:06 INFO]: ==> method: hashCode
[12:09:06 INFO]: ==> method: getClass
[12:09:06 INFO]: ==> method: notify
[12:09:06 INFO]: ==> method: notifyAll
```
So the class still can be loaded but does not contain all methods, which is a contradiction, because ClassGraph verbose log displays methods like `setKey(K)`.

**=>** I think that the IDE does not remove classes from the classpath when clicking the `Delete class` button. Is there a solution to this problem?


> By the way there are a couple of issues with your code:

Thank you, I have improved these issues.

**Comment by lukehutch** [comment] 2019-12-22 22:34
> I think that the IDE does not remove classes from the classpath when clicking the Delete class button. Is there a solution to this problem?

A clean and/or rebuild should do it, but that's an IDE issue, not a ClassGraph issue. I don't use IntelliJ, so honestly I have no idea how to do this, or why it's not properly rebuilding when you delete a class. I would assume this is not the intended behavior of the IDE -- it should rebuild anytime you do anything as drastic as deleting a class.

It's very strange that the `getKey` method is in the loaded class, but the `setKey` method is not. Are you using `getMethod` or `getDeclaredMethod`? Is `setKey` declared in the superclass, but `getKey` declared in the class itself?

Those hasteb.in links don't work -- they take forever to load, then only one of them shows any content, but I can only see a couple of screenfuls and the rest is black. Then eventually I get a tab not responding warning on both tabs.

What I was looking for in the logs though was above the point that you quoted -- I wanted to see which classpath element contained the classfile for the deleted class. Figuring out which classpath element was involved might give you some clues as to why the classfile wasn't deleted when the source file was deleted.

**Comment by PXAV** [comment] 2019-12-23 19:01
> Those hasteb.in links don't work

Here are the logs as text files, maybe you can read them properly now :)
[message_1_log.txt](https://github.com/classgraph/classgraph/files/3995946/message_1_log.txt)
[message_2_log_1.txt](https://github.com/classgraph/classgraph/files/3995947/message_2_log_1.txt)
[message_2_log_2.txt](https://github.com/classgraph/classgraph/files/3995948/message_2_log_2.txt)

I will try to find out whether it really is an IDE error and if yes how to fix it.

**Comment by lukehutch** [comment] 2019-12-23 19:33
Here's the relevant line that shows which classpath element the classfile was found in:

```
2019-12-22T12:09:06.323+0100	ClassGraph	-- Scanning jarfile classpath element /home/pxav/Desktop/Spigot Servers/1.8 Server/plugins/core-1.0-SNAPSHOT.jar (took 0.009557 sec)
```

This looks like a Maven-built jar. So IntelliJ's Maven support is not properly re-building the project when you delete classes. This is definitely not a ClassGraph bug. Also you said 

> When I looked in the jar file (using default archive manager) the .class file still appeared in its package, which would mean the IDE (IntelliJ IDEA) has not deleted the class correctly.

In both scan logs from message 2, the `NbtTag` class is coming from a different classpath element:

```
2019-12-22T12:09:06.324+0100	ClassGraph	-- Scanning jarfile classpath element /home/pxav/Desktop/Spigot Servers/1.8 Server/kelp_versions/v1_8_implementation-1.0-SNAPSHOT.jar (took 0.015634 sec)
```

If ClassGraph is finding that class, it must be there in the jar. ClassGraph can't find something that's not there.

**Comment by lukehutch** [comment] 2019-12-24 13:01
I'm going to close this, because I don't see any evidence that ClassGraph is doing anything wrong here, but feel free to keep asking questions, and I'll reopen it if you find a bug.

**Closed by lukehutch** 2019-12-24 13:01 UTC
