### ISSUE TITLE
ClassInfoList#getNames is not accessible 

### ISSUE THREAD

**Issue by eddi-weiss** [classgraph/classgraph#321] opened 2019-02-22 09:27 UTC
Your provided example:
`try (ScanResult scanResult = new ClassGraph().enableAllInfo().whitelistPackages("com.xyz")
            .scan()) {
    ClassInfoList widgetClasses = scanResult.getClassesImplementing("com.xyz.Widget");
    List<String> widgetClassNames = widgetClasses.getNames();
    // ...
}` 
does not work for me. The Problem is "getNames" method. It is declared and implemented in non public class InfoList

PS:
java 8
maven 3.6.0

**Comment by lukehutch** [comment] 2019-02-22 09:50
Strange, I just tried this, and it works fine for me. I'm running in the Eclipse debugger, in JDK 11, in a separate Eclipse project that depends upon the ClassGraph project. My test class is in the default package, which is not a subpackage of `io.github.classgraph`, where `InfoList` resides.

`InfoList` is non-public, but the methods are public, and the `ClassInfoList` subclass is public. I think that means any public inherited methods also become public? What could cause this difference in visibility enforcement between your environment and mine?

**Comment by lukehutch** [comment] 2019-02-22 10:01
I also tested this with the JDK javac, running from the commandline, and manually adding the classgraph-4.8.5 jar to the classpath, and this succeeded too. Can you please provide a test project that demonstrates the problem?

**Comment by lukehutch** [comment] 2019-02-24 06:48
@eddi-weiss Any progress on reproducing this? I have tried several ways to reproduce what you're seeing, and can't trigger the problem.

**Comment by eddi-weiss** [comment] 2019-02-25 08:51
@lukehutch : I could reproduce it only within maven build (maven 3.6, and java 1.8). If I run my tast inside eclipse, then the test is green. Strange I think JDT compiler works different at this point as a native java compiler. I will create a pull-request with my test. Please take a look on that.

 I also found an intresting article on stackoverflow: https://stackoverflow.com/questions/5260467/public-methods-in-package-private-classes

**Comment by eddi-weiss** [comment] 2019-02-25 08:55
PR is created

**Comment by eddi-weiss** [comment] 2019-02-25 09:00
This is the log output of my build:
```
[INFO] Running io.github.test.classgraph.issues.issue321.ClassInfoListTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.015 s <<< FAILURE! - in io.github.test.classgraph.issues.issue321.ClassInfoListTest
[ERROR] testNames(io.github.test.classgraph.issues.issue321.ClassInfoListTest)  Time elapsed: 0.014 s  <<< ERROR!
java.lang.IllegalAccessError: tried to access class io.github.classgraph.InfoList from class io.github.test.classgraph.issues.issue321.ClassInfoListTest
	at io.github.test.classgraph.issues.issue321.ClassInfoListTest.lambda$testNames$0(ClassInfoListTest.java:30)
	at io.github.test.classgraph.issues.issue321.ClassInfoListTest.testNames(ClassInfoListTest.java:30)

[INFO]
```

**Comment by lukehutch** [comment] 2019-02-25 09:39
I might not be surprised to see this in JDK 9+, due to encapsulation, but it is very strange in JDK 8...

The StackOverflow page you linked to says:

> When a package-private class is inherited by a pubic subclass (of the same package, this is a must), its public methods are inherited as public methods, and thus they become public methods in a pubic class.

I tried your test, and I cannot get it to fail, either in Eclipse, or by calling `mvn test`, on either JDK 8 or JDK 11...

**Comment by lukehutch** [comment] 2019-02-25 09:42
I can make the InfoList class public, but I was trying to limit the number of classes that are publicly visible. And I would like to understand why this is failing only in your JDK environment, and not mine!

Are you running on Windows or something? (I'm on Linux...) Not that that should matter at all here...

**Comment by lukehutch** [comment] 2019-02-25 09:47
@eddi-weiss Ah, this is a Maven problem, due to Maven pulling in `tools.jar` in order to call `javac`, which causes it to use its own `ClassLoader`. It is the spanning of two different classloaders that causes the difference in visibility: https://stackoverflow.com/questions/36100552/illegalaccesserror-when-using-a-public-method-reference-of-a-package-private-cla

**Comment by lukehutch** [comment] 2019-02-25 09:48
It was fixed in JDK8u102 -- are you using a version before that?
https://stackoverflow.com/questions/39112471/java-lang-illegalaccess-on-collecting-guava-immutable-table-via-hashbasedtable-a/39120603#39120603

**Comment by lukehutch** [comment] 2019-02-25 09:51
It definitely looks like this is the issue: https://stackoverflow.com/a/10470249/3950982 And this has been hit by quite a lot of people...

Now that the origin of the problem is clear, it probably makes sense to make that class public.

Thanks for helping me track this down!

**Comment by lukehutch** [comment] 2019-02-25 10:03
Fixed and released in 4.8.8. Thanks!

**Closed by lukehutch** 2019-02-25 10:03 UTC

**Comment by eddi-weiss** [comment] 2019-02-25 10:24
@lukehutch : My java version is 8u91.

**Comment by lukehutch** [comment] 2019-02-25 10:44
It would be interesting to see if JDK8u102 or later fixes the problem. If so, this is the bug that was fixed:

https://bugs.openjdk.java.net/browse/JDK-8152643
