### ISSUE TITLE
Resources in Spring Boot artifacts return the wrong URL

### ISSUE THREAD

**Issue by michael-simons** [classgraph/classgraph#505] opened 2021-03-22 15:02 UTC
Hi Luke.

This is basically the sequel to #435. A user has brought to my attention that the release 4.8.91 (see https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.91) returns invalid class path element URIs for packaged resources in this  https://github.com/michael-simons/neo4j-migrations/issues/179 ticket.

Find a reproducer attached. *NOTE: The thing must be packaged with `mvn clean package` and executed with `java -jar target/classgraph_resources_issue-0.0.1-SNAPSHOT.jar`, running from the IDE is not enough. Commands are shown below so that you don't have to change anything in the pom to switch versions:*

Reproducer: [classgraph_resources_issue.zip](https://github.com/classgraph/classgraph/files/6183167/classgraph_resources_issue.zip)

The core issue is demonstrated between here:

```java
try (ScanResult scanResult = new ClassGraph()
	.whitelistPaths("foo").scan()) {
	List<Resource> resources = scanResult.getResourcesWithExtension("cypher")
		.stream()
		.collect(Collectors.toList());

	resources.forEach(System.err::println);
	if (resources.size() > 1) {
		throw new RuntimeException(":(");
	}

	System.err.println("Reading via Resource#open");
	try (InputStream in = resources.get(0).open()) {
		System.err.println(readInputStream(in));
	} catch (IOException e) {
		e.printStackTrace();
	}

	System.err.println("Reading via Resource#getURL().openStream()");
	System.err.println("URL is " + resources.get(0).getURL());
	try (InputStream in = resources.get(0).getURL().openStream()) {
		System.err.println(readInputStream(in));
	} catch (IOException e) {
		e.printStackTrace();
	}
}
```

*Classgraph 4.8.90*

Run with

```
mvn clean package -Dclassgraph.version=4.8.90 && java -jar target/classgraph_resources_issue-0.0.1-SNAPSHOT.jar
```

Expected output

```
jar:file:/Users/msimons/Downloads/cg/classgraph_resources_issue/target/classgraph_resources_issue-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes/foo/a.cypher
Reading via Resource#open
asd
Reading via Resource#getURL().openStream()
URL is jar:file:/Users/msimons/Downloads/cg/classgraph_resources_issue/target/classgraph_resources_issue-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes/foo/a.cypher
asd
```

*Classgraph 4.8.102*

Run with

```
mvn clean package -Dclassgraph.version=4.8.102 && java -jar target/classgraph_resources_issue-0.0.1-SNAPSHOT.jar
```

Resolving fails (notice the double `BOOT-INF`). I expect that `getURL` returns something that is immediate usable, too.

```
jar:file:/Users/msimons/Downloads/cg/classgraph_resources_issue/target/classgraph_resources_issue-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/BOOT-INF/classes/foo/a.cypher
Reading via Resource#open
asd
Reading via Resource#getURL().openStream()
URL is jar:file:/Users/msimons/Downloads/cg/classgraph_resources_issue/target/classgraph_resources_issue-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/BOOT-INF/classes/foo/a.cypher
java.io.FileNotFoundException: JAR entry BOOT-INF/classes/foo/a.cypher not found in /Users/msimons/Downloads/cg/classgraph_resources_issue/target/classgraph_resources_issue-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes
```

**Comment by lukehutch** [comment] 2021-03-22 20:25
Thanks, looking into the cause. 

However I just wanted to point out that it's not a good idea to open `Resource` streams via their URL, e.g.:

```
            try (InputStream in = resources.get(0).getURL().openStream()) {
                System.err.println(readInputStream(in));
            } catch (IOException e) {
                e.printStackTrace();
            }
```

but instead, just use `Resource#open()`, since this will figure out the best way to open the URL, no matter what the classloader:

```
            try (InputStream in = resources.get(0).open()) {
                System.err.println(readInputStream(in));
            } catch (IOException e) {
                e.printStackTrace();
            }
```

Also in your test code, you are appending lines without also appending the newline characters in between the lines:

```
            String line;
            while ((line = reader.readLine()) != null) {
                sb.append(line);
            }
```

This needs at a minimum an additional `sb.append('\n');` (although this may add an extra newline at the end of a file that does not end in a newline).

In fact if you have lots of resources to iterate through, and you want to load them all, just use `ResourceList#forEachInputStreamThrowingIOException`, `ResourceList#forEachByteArrayIgnoringIOException`, or `ResourceList#forEachByteBufferIgnoringIOException`, and you can avoid this:

```
            resources.forEachByteArrayIgnoringIOException((resource, byteArray) -> {
                String fileContent = new String(byteArray, StandardCharsets.UTF_8);
                // ...
            });
```

Also, this has nothing to do with the bug report, but I'm trying to convert the whole Java world across to the following form, which avoids polluting the namespace with a variable that is only used in the loop :-)

```
            for (String line; (line = reader.readLine()) != null; ) {
                // ...
            }
```

I'll go look for the source of the URL bug.

**Comment by michael-simons** [comment] 2021-03-22 21:06
Thanks.

The test code is only for demonstrating the issue, not something from
production.

The URL is used for two purposes:
- decoupling from the actual discovery of things
- lazy loading possible resources

This is the actual piece using the url of the resource. Don’t want to pass
either resource nor inputstream around:

https://github.com/michael-simons/neo4j-migrations/blob/master/neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/CypherBasedMigration.java#L198

Cheers,
Michael.

Am 22.03.2021 um 21:25 schrieb Luke Hutchison ***@***.***>:

﻿

Thanks, looking into the cause.

However I just wanted to point out that it's not a good idea to open
Resource streams via their URL, e.g.:

            try (InputStream in = resources.get(0).getURL().openStream()) {
                System.err.println(readInputStream(in));
            } catch (IOException e) {
                e.printStackTrace();
            }

but instead, just use Resource#open(), since this will figure out the best
way to open the URL, no matter what the classloader:

            try (InputStream in = resources.get(0).open()) {
                System.err.println(readInputStream(in));
            } catch (IOException e) {
                e.printStackTrace();
            }

Also in your test code, you are appending lines without also appending the
newline characters in between the lines:

            String line;
            while ((line = reader.readLine()) != null) {
                sb.append(line);
            }

In fact if you have lots of resources to iterate through, and you want to
load them all, just use ResourceList#forEachInputStreamThrowingIOException,
ResourceList#forEachByteArrayThrowingIOException, or
ResourceList#forEachByteBufferThrowingIOException, and you can avoid this:

            resources.forEachByteArrayThrowingIOException((resource,
byteArray) -> {
                String fileContent = new String(byteArray,
StandardCharsets.UTF_8);
                // ...
            });

Also, this has nothing to do with the bug report, but I'm trying to convert
the whole Java world across to the following form, which avoids polluting
the namespace with a variable that is only used in the loop :-)

            for (String line; (line = reader.readLine()) != null; ) {
                sb.append(line);
            }

I'll go look for the source of the URL bug.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/classgraph/classgraph/issues/505#issuecomment-804370046>,
or unsubscribe

**Comment by lukehutch** [comment] 2021-03-22 21:52
Yes, I know the repro code wasn't supposed to be production code :-)  (Thanks for the code, as always!)

If all your work is with Spring / Spring Boot, then accessing resources via URLs should always work, I agree. There are just so many weird ways people specify a classpath, which is why I suggested opening via `Resource#open()` is more robust. But if you definitely need to open from URLs, this should work for Spring.

I believe I fixed the issue, released as version 4.8.103. Please test and let me know if it works for you.

Thanks!

**Comment by michael-simons** [comment] 2021-03-23 10:37
Thank you very much for the quick fix. Works for `neo4j-migrations` and after battling failsafe and Spring Boot's fat jar for a while, I have a working integration test, too.

**Comment by lukehutch** [comment] 2021-03-23 11:07
Awesome, thanks for reporting back!

**Closed as completed by lukehutch** 2021-03-23 11:07 UTC
