### ISSUE TITLE
Classgraph holds lock on file

### ISSUE THREAD

**Issue by alexsuter** [classgraph/classgraph#290] opened 2018-12-10 12:45 UTC
On windows i'm facing the issue, that ClassGraph seems to hold a lock on the scanned ressources. After the scanning i'm not able to delete files in the scanned directory.

I could not find any api, which would prevent this behavior. Maybe this is a bug?

```java
public static void main(String[] args) throws IOException {
    ClassGraph classGraph = new ClassGraph()
            .overrideClasspath(new File("C:\\temp"))
            .verbose()
            .enableAllInfo();

    ClassInfoList info = getAllClasses(classGraph);
    System.out.println(info.size());
    
    File f = new File("C:\\temp\\org\\apache\\commons\\io\\comparator\\SizeFileComparator.class");
    Files.delete(f.toPath());
}

private static ClassInfoList getAllClasses(ClassGraph classGraph) {
    try (ScanResult result = classGraph.scan())
    {
      return result.getAllClasses();
    }
}
```

In this case ` Files.delete(f.toPath())` throws the following exception:

```
Exception in thread "main" java.nio.file.FileSystemException: C:\temp\org\apache\commons\io\comparator\ReverseComparator.class: The process cannot access the file because it is being used by another process.
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at ch.ivyteam.ivy.java.restricted.AnnotatedTypes.main(AnnotatedTypes.java:74)
```

[verbose.log](https://github.com/classgraph/classgraph/files/2663137/verbose.log)

**Comment by lukehutch** [comment] 2018-12-10 13:13
Zipfiles are held open (actually mmap'd) while the ScanResult is open, since opening zipfiles is costly, and that caused a related issue on Windows (#288).

However, files within directory (non-jar) classpath elements should not be held open after scanning, so this would be a bug.

The code does attempt to close any underlying InputStream or ByteBuffer to the file though:

https://github.com/classgraph/classgraph/blob/master/src/main/java/io/github/classgraph/ClassfileBinaryParser.java#L728

Can you please set a breakpoint on that line and see if the file is not being closed properly for some reason?

**Comment by alexsuter** [comment] 2018-12-10 14:49
I can confirm that `close `will called and no `IOException `will be thrown.

**Comment by alexsuter** [comment] 2018-12-10 15:03
Before entery method `readClassInfoFromClassfileHeader` there is no file lock.

1. After calling `openOrRead()` it seems that we have two file locks.
2. After calling `close` there is one file lock left.

**Comment by lukehutch** [comment] 2018-12-10 22:23
@alexsuter The problem is the same as the problem in #288, that just having a `MappedByteBuffer` reference sitting around somewhere counts as one file lock in the JRE on Windows.

I just committed a change to master that more agressively drops these `MappedByteBuffer` references after they are used. This will improve the problem. In particular, there was one "phantom" reference being held in a synthetic inner class accessor, and that has been fixed.

However, Windows can only clear these file locks when the garbage collector actually cleans up these `MappedByteBuffer` objects. The fix for #288 was to call `System.gc()` on `ScanResult#close()` on Windows. (Other operating systems don't need this fix.) With the new version in master, at least outside of your `try (ScanResult scanResult = new ClassGraph() [...] .scan()) { ... }` block, you should no longer see any locks held. However, if you want to delete classfiles or resources *inside* the try-with-resources block, you will have to manually call `System.gc()` before `Files.delete()`.

Can you please verify these two things with the master version?:

1. The file lock is no longer held outside the try-with-resources block.
2. If you call System.gc(), you can delete formerly locked classfiles or resources "early" within the try-with-resources block.

Thanks!

**Comment by lukehutch** [comment] 2018-12-10 22:53
I pushed out version 4.6.7 to make it easier to test. Thanks!

**Comment by alexsuter** [comment] 2018-12-11 06:52
Great thanks. I will test it today. Yes, I don't need to delete any files within try ... with ... resources

**Comment by lukehutch** [comment] 2018-12-11 07:09
I dug around some more and found this is a famous and well-desipsed problem with using mmap in Java on Windows. The recommendation is to simply not use mmap:

http://www.mapdb.org/blog/mmap_files_alloc_and_jvm_crash/

I just checked in some code that disables mmap for `Resource` open/read/load methods on Windows, for directory classpath entries. (These methods are also used for reading classfiles.) This will result in a 10-20% decrease in performance for classfile reading, but only for classpath entries that are stored uncompressed as a hierarchy of files on disk, which is often or usually a small percentage of the total classfiles scanned in a complex project. Jarfile classpath entries and modules will still scan at full speed.

ClassGraph still uses mmap to open jarfiles on Windows, since this is the most efficient way to deal with them. These `MappedByteBuffer` references should be freed on `ScanResult#close()`.

I won't push out a new release just yet for the fix, since 4.6.7 should be an adequate fix for now, but in the long run the right fix is to minimize mmap usage on Windows. The latest change will be in 4.6.8 whenever that is released.

I'll close this for now, but please do let me know if 4.6.7 fixes the problem for you (it should do so). Thanks for the bug report!

**Comment by GedMarc** [comment] 2018-12-11 07:58
So I'm really curious about this one! And would love to learn more on it -

In this article, he highlights the main problem as the directory/paths reader, and highlights that mmap should not be used (in any os) for files smaller than 6MB, 
https://hk.saowen.com/a/b91e4cbff81c94339a3dbcd3a3064887bdf42ac9381597c6f540beb604834a12

Going down the rabbit hole a bit further, in looking at performance (from what I understand), the nio directory walker running through a parallel stream outperforms the mmap when in a directory hierarchy 6 levels deep with 10k files (most under 6mb) - which I think is a pretty standard setup for exploded execution? As long as you don't pull the file information I guess?
https://www.rgagnon.com/javadetails/java-get-directory-content-faster-with-many-files.html

So in order to learn a bit more, why was mmap chosen for exploded files, class files will generally never hit 6mb in size, and what was the choice behind not directory walking/scanning (DirectoryWalker.stream.parallel()) from nio?
A lot of references also seem to highlight that if you're not doing random file access, you shouldn't be using mmaps either?
I don't know much about this, but it feels like mmap's are incredibly "task" or "application" specific, and not really for general use?

```
The reason mmap is faster is the file is not all read into memory at once. The file is mapped against an address in memory, and you can access it in a non sequential way without loading the parts of the file you don't need to process.
This is sort of application specific, but it's really meant for large files that are only partially processed and files that wouldn't normally fit into memory. There are other use cases such as shared memory and shared objects. Dynamically linked libraries are loaded using mmap so that they do not need to be loaded from the disk for every process that wants to use them. The second process to use a shared library is actually looking at the same physical memory as the first process.
```

**Comment by lukehutch** [comment] 2018-12-11 08:35
The way to think about the difference in speed is that opening a file with an `InputStream` as `O(aN + b)` vs. `mmap` as `O(cN + d)`. The initial startup time will be different (`b` vs. `d`) and the throughput will be different (`a` vs. `c`).

That first link is for Go, not Java, which will have different values for all of `a`, `b`, `c` and `d` than Java, so it doesn't help much. In my own benchmarking (and benchmarking run by a few users, including you, I think, @GedMarc!), showed that in Linux and Mac OS X, `mmap` was 2-5% slower than `InputStream` up to 16kB (not 6MB), then `mmap` became faster, and the speedup increased linearly with the filesize, up to 1MB or so (I didn't test bigger sizes than this). (The increase not being constant indicates that the actual latency and bandwidth numbers for the two methods are not actually constant, but are a function of filesize to some extent.)

As far as parallelism: yes, parallelism actually affects the linear equations I gave above, and makes them even more non-linear :-)  And the behavior will be very different on an SSD vs. an HDD, since an HDD has to seek.

> A lot of references also seem to highlight that if you're not doing random file access, you shouldn't be using mmaps either?

The API for using a `MappedByteBuffer` is generally much simpler than the one for `SeekableStream`, and this is a big reason to prefer `mmap`. But on modern operating systems, `mmap` is not a slow operation, and the VM logic to swap pages in when a page fault occurs and swap them out when not needed using an LRU list is pretty highly optimized. I don't see a lot of downsides.

> The reason mmap is faster is the file is not all read into memory at once.

There is a call `MappedByteBuffer#load()`, but if you don't call that, then yes, the pages are pulled in on-demand.

It's possible that's going to be more optimal than `InputStream`, since the buffer size of `InputStream` may not be a sensible multiple of (or factor of) to the VM page size. However neither the `InputStream` buffer size nor the VM page size may be appropriately tuned to the sector size or block size of the disk, so you might end up loading more than you need, or (less likely) wasting time by loading less than a complete sector or block.

It's all complicated, and there's no real answer other than benchmarking on a specific hardware platform and with a specific filesystem and set of files.

I think using `mmap` for >16kb for non-Windows systems is probably a reasonable thing to do, based on benchmarking. The only issue that could be hit is that there are only 64k concurrent `mmap`s allowed on Linux. I checked in a `System.gc()` call tonight that is triggered if that limit is hit, which will hopefully free unused `MappedByteBuffer` instances and fix the `OutOfMemoryError` problem before the VM crashes.

I don't know what the number of allowed concurrent `mmap` operations is on Mac OS X, but if you or someone can test it out and let me know, it would be great:

```java
        final File file = File.createTempFile("mmapd", "file");
        try (PrintWriter p = new PrintWriter(file)) {
            p.println("test");
        }
        final RandomAccessFile raf = new RandomAccessFile(file, "r");
        final FileChannel fc = raf.getChannel();
        final List<ByteBuffer> bufs = new ArrayList<>();
        for (final int i = 0; i < 1_000_000;) {
            if (bufs.size() % 1000 == 0) {
                System.out.println(bufs.size());
            }
            try {
                final MappedByteBuffer buf = fc.map(FileChannel.MapMode.READ_ONLY, 0, 5);
                bufs.add(buf);
            } catch (IOException | OutOfMemoryError e) {
                System.out.println("Ran out of mmaps at iteration: " + i);
                System.exit(1);
            }
        }
```

> Dynamically linked libraries are loaded using mmap so that they do not need to be loaded from the disk for every process that wants to use them. 

This would explain why WildFly extracts any .so files it finds into temporary dirs (discovered while fixing the recent WildFly bug...)

**Comment by lukehutch** [comment] 2018-12-11 08:35
@alexsuter Great, thanks for reporting back!

**Comment by jechlin** [comment] 2019-01-02 09:13
Hi Luke, thanks for your great work on this project, we have been using it for several years.

I encountered a problem where with an old version of fast-classpath-scanner, on Windows, a jar file was locked and could not be deleted after doing a scan, in a spring boot application. This didn't occur when not using spring boot, so I'm deducing that it's something to do with a URL handler for jar files that spring boot installs, although I couldn't pinpoint it exactly.

Anyway, I upgraded to the latest version of ClassGraph - the problem is that System.gc() takes 300ms-500ms, and as we sometimes need to make several scans in a single rest request this makes our app much slower.

I just wondered if you had any advice. Ideally I think it would be better if you didn't use mmap on Windows, given the problems it seems to cause. Failing that, is it possible to add an option not to call the .gc(), then we can call for a gc manually when we actually want to delete the file.

I tried just not calling ScanResult.close(), but I still can't delete the file even after GC, I guess because other streams are open (expected).

For context this is an OSGi application, so installing/uninstalling bundles requires jar files to be deleted.

**Comment by lukehutch** [comment] 2019-01-02 21:18
> Hi Luke, thanks for your great work on this project, we have been using it for several years.

I'm glad you're getting some good use out of it!

> I encountered a problem where with an old version of fast-classpath-scanner, on Windows, a jar file was locked and could not be deleted after doing a scan, in a spring boot application. This didn't occur when not using spring boot, so I'm deducing that it's something to do with a URL handler for jar files that spring boot installs, although I couldn't pinpoint it exactly.

It's definitely due to this old issue you found, and it has come up repeatedly. If the problem persists after the most recent changes (see below), and they seem to be caused by ClassGraph and not Spring Boot, please let me know.

> Anyway, I upgraded to the latest version of ClassGraph - the problem is that System.gc() takes 300ms-500ms, and as we sometimes need to make several scans in a single rest request this makes our app much slower.

mmap is used in two different places in ClassGraph: (1) to open jarfiles (from which resources, including classfiles, are read directly); and (2) to open individual files from the filesystem, for directory classpath elements.

In ClassGraph 4.6.7, I disabled mmap usage (2) on Windows, because of the problems it could cause. However, I should have also removed the `System.gc()` call, since this is no longer needed, except for the case of jarfiles that needed to be removed.

I just checked in a change that removes the `System.gc()` call on Windows. Now the remaining problem is (1), in this case:

> For context this is an OSGi application, so installing/uninstalling bundles requires jar files to be deleted.

I added the StackOverflow code you linked to PhysicalZipFile, and also to Resource for good measure (so that `MappedByteBuffer` instances are closed immediately on non-Windows operating systems) -- thanks for this link. Can you please test the git master version?

It is very possible that this will break at some point, because the cleaner mechanism uses a Sun internal API. Can you please take a look to see if it looks like this method still works in JDK11, and if not, can you please send a PR that updates the reflective code in `Resource` and `PhysicalZipFile` to work on both JDK7/8 and JDK9-11?

**Comment by jechlin** [comment] 2019-01-03 12:05
Thanks for your response Luke.

First of all, your recent commit works fine on JDK8, I added a simple test which attempts to delete the jar that fails without your recent change, and works with it. 

With JDK 11, first I tried `jdk.internal.ref.Cleaner` which seems to be where sun.misc.Cleaner got moved to.  As well as getting the warning you mentioned (which I believe is only printed the first time this happens), I got:

    java.lang.reflect.InaccessibleObjectException: Unable to make public void jdk.internal.ref.Cleaner.clean() accessible: module java.base does not "exports jdk.internal.ref" to unnamed module @1efbd816

I am trying openjdk11, but I get the same result with oracle jdk 11. I think what must be happening for you is that you get a CNFE for `sun.misc.Cleaner`, then it's falling through to the empty exception handler. Net result is that the test fails with:

    java.nio.file.FileSystemException: C:\tmp\xxx.jar: The process cannot access the file because it is being used by another process.

`java.lang.ref.Cleaner` seems to be the way to go but honest I am not quite sure how to use it, I feel slightly out of my depth. 

Come to think of it - if you are happy with your removal of the `System.gc()` for windows only - I can work round this problem by doing a full GC on Windows, when I know that the jar file will be deleted. The overhead of the GCs (when they were mostly not required), was what was really hurting me.

Not sure of the value of leaving the current cleaning in... obviously it will have no effect after jdk 8, except for logging the ugly message.

**Comment by lukehutch** [comment] 2019-01-03 13:21
Since the Cleaner version doesn't currently work on JRE 9+, I could enable it only for JRE 7-8. Then there wouldn't be a warning printed. But it will then be up to you (or the user, in general) to call System.gc() manually before removing jars for JRE 9+ (which will quickly become the standard JRE, specifically JRE 11).

I wonder if it would be a good idea to create softlinks to the jars, and delete those instead. Then ClassGraph could watch those softlinks, and if they disappear, it could call System.gc() on JRE 9+. Just an idea.but the caller would have to set things up this way.

**Comment by lukehutch** [comment] 2019-01-04 05:16
> > But it will then be up to you (or the user, in general) to call System.gc() manually before removing jars for JRE 9+
> 
> That seems reasonable to me.

Committed.

Please ask around on one of the openjdk mailing lists to see if there is an equivalent to the `clean()` method using `Cleaner` on JDK 9+. I don't know why forcibly unmapping a `MappedByteBuffer` is not a supported API call.

**Comment by johnou** [comment] 2019-01-04 06:37
@lukehutch the cleaner does work on jdk 9+ see https://raw.githubusercontent.com/atomix/atomix/master/utils/src/main/java/io/atomix/utils/memory/BufferCleaner.java

**Comment by lukehutch** [comment] 2019-01-04 08:10
@johnou great find! I'll add in that code. That should solve the problem for good.

Maybe I should re-enable mmap for Windows then, for directory-based classpath entries? It's something like 10-15% faster than `InputStream`.

**Comment by lukehutch** [comment] 2019-01-04 19:22
@johnou `Unsafe.invokeCleaner()` just does this:

```java
    public void invokeCleaner(java.nio.ByteBuffer directBuffer) {
        if (!directBuffer.isDirect())
            throw new IllegalArgumentException("buffer is non-direct");

        DirectBuffer db = (DirectBuffer)directBuffer;
        if (db.attachment() != null)
            throw new IllegalArgumentException("duplicate or slice");

        Cleaner cleaner = db.cleaner();
        if (cleaner != null) {
            cleaner.clean();
        }
    }
```

So that Atomix code is just a fancy way to achieve the same thing as the code linked by @jechlin.

N.B. I noticed that almost all methods in `sun.misc.Unsafe` pass through directly to correspondingly-named methods in `jdk.internal.misc.Unsafe`, but `Unsafe.invokeCleaner()` does not. I don't know what that means (maybe `invokeCleaner()`, or the `DirectByteBuffer::clean()` method, may not be supported in a future release).

**Comment by lukehutch** [comment] 2019-01-04 20:03
I tested, and yes, the difference is that the `Unsafe::invokeCleaner` method does not print the reflection warning. This is therefore called in JDK 9+.

Released in ClassGraph 4.6.11.

This may need to be revisited one day if the `sun.misc.Unsafe` class is removed (but I imagine there will be an outcry if `java.internal.misc.Unsafe` doesn't get a corresponding `invokeCleaner()` method at that time).

Thanks everyone for help in getting this sorted out!

**Closed by lukehutch** 2019-01-04 20:03 UTC

**Comment by lukehutch** [comment] 2019-01-04 21:30
I made a robustness fix (duplicated ByteBuffers and slices should not be freed in JDK 7/8), and also discovered that you need `requires jdk.unsupported` in a module descriptor for JDK 9+ if you want to use `Unsafe`. Pushing out a new version, 4.6.12.

**Comment by GedMarc** [comment] 2019-01-06 17:04
Please please please do not use Unsafe, jdk.unsupported will be required in modular and it is going to be removed. Is there any way to make this optional??? As an enabled feature to hit this class?? In the moditect you can then requires static jdk.unsupported and it doesn't impact the user.

This is gonna be a killer for me. Jdk.unsupported is not a transient dependency and has to be included in the base module no matter what or how you specify your module base.

Please please, noooooooooo

On 4 Jan 2019 21:22, Luke Hutchison <notifications@github.com> wrote:

@johnou<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnou&data=02%7C01%7C%7C61d2b8be25804fbd4b2308d6727a080e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636822265769935393&sdata=49mODjYZ5hT6kbmvhEYiEZ5Yv8Ly7QapZM4gUO76gWw%3D&reserved=0> Unsafe.invokeCleaner() just does this:

    public void invokeCleaner(java.nio.ByteBuffer directBuffer) {
        if (!directBuffer.isDirect())
            throw new IllegalArgumentException("buffer is non-direct");

        DirectBuffer db = (DirectBuffer)directBuffer;
        if (db.attachment() != null)
            throw new IllegalArgumentException("duplicate or slice");

        Cleaner cleaner = db.cleaner();
        if (cleaner != null) {
            cleaner.clean();
        }
    }

So that Atomix code is just a fancy way to achieve the same thing as the code linked by @jechlin<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjechlin&data=02%7C01%7C%7C61d2b8be25804fbd4b2308d6727a080e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636822265769935393&sdata=i9b%2Fnzit09hDg5mnKTRN84kSAXdVXG%2F9Op5tH%2Big5vo%3D&reserved=0>.

N.B. I noticed that almost all methods in sun.misc.Unsafe pass through directly to correspondingly-named methods in jdk.internal.misc.Unsafe, but Unsafe.invokeCleaner() does not. I don't know what that means (maybe invokeCleaner(), or the DirectByteBuffer::clean() method, may not be supported in a future release).

**Comment by GedMarc** [comment] 2019-01-06 20:20
I just moved so house internet not installed yet and can't really check.

Jdk.unsupported has a few things about it that make it a do-not-use, I know on helping the hazelcast guys all access to it had to be removed entirely.

There *should* be no reason to access anything in that module, but if we've somehow found a case for it, it is better to extract the code into its own classes than actually reference the module!!

If you have to, which I really do strongly doubt, again can't know for sure no internet, then make it transitive in moditect, it has to be placed in the base module somehow because of the effects on the JVM it has by just including it.

I strongly think this is the incorrect approach to this problem.



On 6 Jan 2019 20:23, Johno Crawford <notifications@github.com> wrote:

@GedMarc<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGedMarc&data=02%7C01%7C%7C852be17eaa374461891008d67404056c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636823957945576897&sdata=j9OSJ7yidadEn0uPZks1qn3064SfK7N0%2BGMwwBwrhrI%3D&reserved=0> it looks optional to me.

**Comment by lukehutch** [comment] 2019-01-07 04:16
@GedMarc please do not use Outlook to respond to GitHub messages -- take a look at this issue in the web interface to see what it does to your messages. (Now that GitHub is owned by MS, hopefully they fix this...)

> it is better to extract the code into its own classes than actually reference the module!!

In this case, that is impossible. The code called in `sun.misc.Unsafe` in JDK9+ (which I fully quoted a few responses back) is exactly the same as pre-JDK9, but generates an ugly un-suppressable reflective access warning on stderr in JDK9+. Only by having the JDK call that code for you in JDK9+ does the warning go away. 

> If you have to, which I really do strongly doubt, again can't know for sure no internet, then make it transitive in moditect,

Make it transitive? All module "requires" statements are non-transitive due to strong encapsulation rules. Users of ClassGraph will not gain access to ClassGraph's modular dependencies, which it sounds like is what you want.

> it has to be placed in the base module somehow because of the effects on the JVM it has by just including it.

What effects? 

`requires static` is a really brittle "solution". The ability to unmap `MappedByteBuffer` instances would mysteriously fail in ClassGraph if the `jdk.unsupported` module didnt make it into the module graph in some other way (being required by some other module, added manually with `--add-modules`, drawn in by service binding, etc.).

They can't remove all of `jdk.unsupported` for a long time, and they will have to provide alternatives before they do. In particular, database makers will *need* a way to manually unmap mapped buffers. Until that exists, this is unfortunately the best solution.

I suggest starting a discussion about this on one of the jdk discussion forums -- if you do, please link it here.

**Comment by lukehutch** [comment] 2019-01-07 10:18
I found this bug, which summarizes the status from Oracle's point of view:

https://bugs.openjdk.java.net/browse/JDK-4724038

It looks like the solution in place in ClassGraph is the best (/only) solution for now, and that there may be a better solution coming in future.

**Comment by lukehutch** [comment] 2019-01-07 14:51
@jechlin thanks for reporting back on your testing. Assume this is "fixed unless the JDK guys decide to break it for everyone" :o)

**Comment by GedMarc** [comment] 2019-01-08 23:46
interesting reads - 
Looks good from my end
