### ISSUE TITLE
Classgraph is not compatible with coursier when using private repositories on JDK 10

### ISSUE THREAD

**Issue by pshirshov** [classgraph/classgraph#255] opened 2018-10-01 21:30 UTC
I'm using classgraph to resolve artifacts in sbt project with coursier.

We have two dependency types:

1. Pusblished on public repositories
2. Published on our private repository

While running under JDK 10 (`OpenJDK 64-Bit Server VM Zulu10.3+5 (build 10.0.2+13, mixed mode)`) within SBT or under Idea classgraph fails to resolve any classes from private repo artifacts. 

At the same time it resolves these classes without an issue in case I gather all the dependencies manually into a directory and run java providing them all as classpath entries.

I'm almost sure that this is happening because of crappy directory naming convention used by coursier:

```
/Users/<user>/Library/Caches/Coursier/v1/https/<username>%40<company>.com%40<company>.jfrog.io/<company>/<repo>/com/<company>/<artifact>/<version>/<name>.jar
```

Seems like classgraphs fails to scan directories with `%` in name.

All such jars are completely missing from classgraph debug output.

**Comment by lukehutch** [comment] 2018-10-01 21:39
@pshirshov it's probably due to accidental unescaping of the %40 at some point in the process of handling the classpath elements. Classpath elements can be URLs or paths, so they can include %-escaped characters in them. %40 would be '@'. There's no reason a filename can't have an '@' in it, I think, on any of the major operating systems, so it's weird that they chose to escape that character in that way.

Please call `.verbose()` before `.scan()`, and attach the logs here, so I can see how the %40 is being handled at different stages.

**Comment by pshirshov** [comment] 2018-10-01 21:53
[out.txt](https://github.com/classgraph/classgraph/files/2435793/out.txt)

**Comment by pshirshov** [comment] 2018-10-01 21:55
[out.txt](https://github.com/classgraph/classgraph/files/2435802/out.txt)

> so it's weird that they chose to escape that character in that way.

I guess they just use URIs.

**Comment by pshirshov** [comment] 2018-10-01 21:56
Here is the output you are looking for:

```
2018-10-01T22:47:15.919+0100	ClassGraph	------ Ignoring invalid classpath element: /Users/USER/Library/Caches/Coursier/v1/https/pshirshov@COMPANY.COM.COMPANY.jfrog.io/COMPANY/REDACTED-releases/COM.COMPANY/api-PRODUCT_2.12/0.13.0/api-PRODUCT_2.12-0.13.0.jar : java.io.IOException: Could not locate file /Users/USER/Library/Caches/Coursier/v1/https/pshirshov@COMPANY.COM.COMPANY.jfrog.io/COMPANY/REDACTED-releases/COM.COMPANY/api-PRODUCT_2.12/0.13.0/api-PRODUCT_2.12-0.13.0.jar -- resolved to: /Users/USER/Library/Caches/Coursier/v1/https/pshirshov@COMPANY.COM.COMPANY.jfrog.io/COMPANY/REDACTED-releases/COM.COMPANY/api-PRODUCT_2.12/0.13.0/api-PRODUCT_2.12-0.13.0.jar
```

**Comment by lukehutch** [comment] 2018-10-01 23:06
This is a pretty ugly thing to deal with -- normally you would not %-encode characters in directory names on disk, that's only for use in URLs. In fact, on Windows, '%' is reserved for the expansion of environment variables, so having that character in a directory name is a really bad idea. It would be much better to just use the '@' character in this case, and you should file a bug with Coursier about this issue.

Nevertheless, to handle this case, I added special-case logic to ClassGraph that does the following: if a directory or jarfile is not found, the path is broken down into segments, and each segment is matched with a directory or file on disk. If a segment is not found, then all files in the parent directory are searched for names containing '%', and those names are '%'-unescaped. If one of those names matches the target segment name (also '%'-unescaped), then the search along the path proceeds, otherwise it fails. This should solve your problem -- please test the master version (`mvn package`). Thanks!

**Comment by pshirshov** [comment] 2018-10-01 23:19
I understand that it's a nightmare to deal with. So I've created a ticket for coursier guys. But they are aware of this problem and very reluctant to fix :/

> please test the master version
Will try. I think it may be a good idea for you to setup a travis build with snapshot publishing?

**Comment by lukehutch** [comment] 2018-10-01 23:43
> Will try. I think it may be a good idea for you to setup a travis build with snapshot publishing?

I already have that:

https://travis-ci.org/classgraph/classgraph

...and I added a unit test that illustrates that the fix works, at least on Linux. But:

1. Travis runs tests on Linux, and you are on Mac OS X -- there are some differences in path handling between these platforms;
2. Even though I wrote a unit test to show that the fix passes, there's a chance it won't fix your exact situation due to unforeseen circumstances. That's why I hope you can test it on your setup before I push out a release (so that I don't have to push out two releases if it doesn't quite fix the problem for you yet).

**Comment by pshirshov** [comment] 2018-10-01 23:46
It works, thank you!

Could you release please?

Actually it's kinda crappy that you had to workaround that issue though it may happen with someone else's configuration, it's not actually specific for coursier.

Though it's still a heuristic :/

**Comment by lukehutch** [comment] 2018-10-01 23:52
Thanks for testing! Sure, I can push out a relase, but this is a very weird and very specialize usecase. It *probably* doesn't hurt to leave the code in ClassGraph, but I'm wondering how many users this really will affect. How widespread is the use of Coursier at this point? Does Coursier auto-upgrade itself when you run it (i.e. fetch the latest version of itself, or something)? If the Coursier team is going to merge the PR that you linked to in the Coursier bug report, which uses hashcodes for user names, will that mean this will quickly become a non-issue?

**Comment by lukehutch** [comment] 2018-10-01 23:54
> it's not actually specific for coursier

I'm pretty sure it is :-)  I have never seen anyone %-encode filenames before... though I imagine this may have happened elsewhere in the universe of all software!

**Comment by pshirshov** [comment] 2018-10-01 23:58
> how widespread

Huge adoption in scala world, many projects are migrating.

> Does Coursier auto-upgrade itself when you run it (i.e. fetch the latest version of itself, or something)? If

Usually people use it as sbt plugin.

>  the Coursier team is going to merge the PR that you linked to in the Coursier bug report, which uses hashcodes for user names, will that mean this will quickly become a non-issue?

Yup, though they are aware of the issue for more than an year and don't want to do anything.

> I'm pretty sure it is :-) 

Well, kinda. I may imagine at least one case when it may affect non-coursier user - LDAP-based user management with full emails in their username (I've seen such a crap once). So `/home/user@company.com/...`. Though yup, it's hard to imagine a percent sign...

**Comment by lukehutch** [comment] 2018-10-02 00:00
`/home/user@company.com/` is totally fine. It's `/home/user%40company.com/` that is the problem.

Fixed and released in 4.2.6. Should be in Maven Central in a couple of hours (Maven Central takes a while to pull from Sonatype).

**Closed by lukehutch** 2018-10-02 00:00 UTC

**Comment by pshirshov** [comment] 2018-10-02 00:02
Aha, thanks a lot!

I guess in case coursier fixes their issue it wouldn't be a problem to drop this patch though. All the potentials problems are very unlikely to happen.

**Comment by lukehutch** [comment] 2018-10-02 00:13
Sure, maybe I'll take it out one day. The only major impact of the patch will be a slowdown for cases where there are directories listed on the classpath that genuinely don't exist, since now if a path initially doesn't exist, I have to iterate through the entire path, segment by segment, to check if any segment is %-encoded in the directory list.

**Comment by lukehutch** [comment] 2018-11-30 10:11
Just as a heads-up, I am changing the behavior of this, for performance reasons: if a classpath entry contains a `'%'` character, the %-decoding logic will not be applied _unless_ the classpath entry is a URL. 

In other words, if your directory on disk is `/home/user%40company.com/jarfile.jar`, your classpath should contain the string `/home/user%40company.com/jarfile.jar`, and _not_ `file:/home/user%40company.com/jarfile.jar` or `jar:file:/home/user%40company.com/jarfile.jar`. If given in the form of a URL, the classpath element will be decoded into the path `/home/user@company.com/jarfile.jar`.

I think this is the most reasonable way to handle this weird and rare corner case. This should not affect your usage, hopefully. The only issue would be if your classpath has jar paths containing nested jars or package root prefixes, e.g. `/home/user%40company.com/jarfile.jar!/BOOT-INF/classes` or `/home/user%40company.com/jarfile.jar!/BOOT-INF/lib/nestedjar.jar`, since these sorts of paths are often prefixed by `jar:` or `jar:file:` in the classpath. (But this is a corner case of a corner case, and hopefully this will not prove to be an issue.)

**Comment by pshirshov** [comment] 2018-11-30 13:22
I'll report back in case of any issues.

**Comment by GedMarc** [comment] 2018-12-01 05:29
Um,  
I'm not sure as to why you are still using JDK 10, but JDK 10 EOL was September 2018... 
JDK 10 is also not an LTS release, and in my experience was completely half-baked.
My experience with it to get things working was awful.

What is the policy for supporting EOL JDK's?

- JDK 6 EOL = December 2018
- JDK 7 EOL = July 2019
- JDK 8 EOL = March 2022
- JDK 9 EOL = March 2018
- JDK 10 EOL = September 2018
- JDK 11 EOL = September 2026

JDK 9 and 10 and reached end of life, you shouldn't be using it anymore?

**Comment by lukehutch** [comment] 2018-12-01 10:44
This bug has nothing to do with JDK 10.

This bug report was triggered by a Coursier bug. Coursier seems to be using something like

```java
File fileToWrite = new File(url.getFile());`
```

(which would leave any %-encoding in place in a URL path string) rather than something like

```java
File fileToWrite = new File(URLDecoder.decode(url.getFile(), "UTF-8"));
```

(which would decode any %-encoding).

**Comment by pshirshov** [comment] 2018-12-01 11:45
> I'm not sure as to why you are still using JDK 10, but JDK 10 EOL was September 2018...
Actually we've already migrated to JDK11 but the behavior was the same on 10/11. Worked on 8/9 so that's why I've guessed that it is related to jdk somehow.

**Comment by lukehutch** [comment] 2018-12-01 12:07
Strange -- there may have been a change in URL or file path handling in JDK 10 that causes this issue.

Either way, ClassGraph 4.6.0 (which implements the new behavior, and should be released soon) should not exhibit a regression, if the classpath is set up as typical (without "file:" or "jar:file:" prefixes on classpath entries).
