### ISSUE TITLE
Find all classes in java that extend a base class

### ISSUE THREAD

**Issue by MaverickLafont** [classgraph/classgraph#426] opened 2020-05-03 18:18 UTC
Hello,

I've a Animal Class that extend other class like Lion, Monkey.. and i want to get all of these classes.

I've read this post "https://stackoverflow.com/questions/205573/at-runtime-find-all-classes-in-a-java-application-that-extend-a-base-class"  but i can't get it to work ..
I've also tried **org.reflections**, but still the same issue.

This is what im actually trying with **classgraph**

`public List<Class<Animal>> getTypeAnimal() {
List<Class<Animal>> animals;
		try (ScanResult scanResult = new ClassGraph().whitelistPackages("org.formation.zoo.modele.metier")
		        .enableClassInfo().scan()) {
		    animals = scanResult
		        .getSubclasses(Animal.class.getName())
		        .loadClasses(Animal.class);
		}
		return animals;
	}`

And this is the error message : 

> Caused by: java.lang.NoClassDefFoundError: io/github/classgraph/ClassGraph
at deployment.correctionzoo2020.war//org.formation.zoo.controleur.Manager.getTypeAnimal(Manager.java:134)
	at deployment.correctionzoo2020.war//org.formation.zoo.controleur.InitServlet.getTypeAnimal(InitServlet.java:60)
	at deployment.correctionzoo2020.war//org.formation.zoo.controleur.InitServlet.doPost(InitServlet.java:41)
	at deployment.correctionzoo2020.war//org.formation.zoo.controleur.InitServlet.doGet(InitServlet.java:29)

> Caused by: java.lang.ClassNotFoundException: io.github.classgraph.ClassGraph from [Module "deployment.correctionzoo2020.war" from Service Module Loader]

it seems like it is a issue with the class ??

**Comment by lukehutch** [comment] 2020-05-03 18:49
It looks like you're including ClassGraph on the traditional classpath rather than the module path, but your custom class is running inside a module. In JDK9+, you can't call back and forth between the two.

**Comment by MaverickLafont** [comment] 2020-05-03 19:33
Im a little bit new in java. I don't really get what you are saying with module path.
Im using JDK11, with JPA, MVC and Manager is the Controller.

So i can't use classgraph inside my controller ?

**Comment by lukehutch** [comment] 2020-05-03 19:38
No, you can definitely use ClassGraph, and what you're trying to do would work. How are you including ClassGraph as a dependency in your project, and how are you running the code? Inside an IDE, or from the commandline?

**Comment by MaverickLafont** [comment] 2020-05-03 19:40
I've imported ClassGraph as a dependecy (inside pom.xml). And i'm running the code inside Eclipse.
By the way thank's for trying solve my issue and sorry for my english, im french.

**Comment by lukehutch** [comment] 2020-05-03 19:49
Pas de problème! Tu parles bien l'anglais.

Can you please zip up your whole project and attach it? I'll take a look.

**Comment by MaverickLafont** [comment] 2020-05-03 20:02
[correctionzoo2020.zip](https://github.com/classgraph/classgraph/files/4571495/correctionzoo2020.zip)

Thank you ! This is my project

**Comment by MaverickLafont** [comment] 2020-05-03 20:45
Oh i forgot to say that my code is running with the **wildfly** server

**Comment by lukehutch** [comment] 2020-05-03 21:00
Oh, can you please give some brief instructions about how to set that up?

**Comment by MaverickLafont** [comment] 2020-05-03 21:06
Oh shit hahaha

**Comment by MaverickLafont** [comment] 2020-05-03 21:14
Well, i've downloaded wildfly, and installed it with jboss tools.
When it's done you can add a new server of type "wildfly 18" (even if the wildfly version is 19, it's ok). You can now right click on initServlet.java and run with the wildfly server.

But there are a lot of step to install the wildfly server, i think it will take to muche time

**Comment by MaverickLafont** [comment] 2020-05-03 21:15
And there is the database launched with wamp

**Comment by MaverickLafont** [comment] 2020-05-03 21:18
I thought that you wanted to take a look at the code. Try to lunch it take to much time

**Comment by lukehutch** [comment] 2020-05-03 21:41
Well if I put a main method in `Manager.java` that just prints out all the `Animal` subclasses, it works:

```
org.formation.zoo.modele.metier.Gazelle
org.formation.zoo.modele.metier.Lion
org.formation.zoo.modele.metier.Singe
```

So ClassGraph itself is working, and instead, there is something broken about how you are launching your code in Wildfly.

The Eclipse project shows that all your Maven dependencies are launched using the traditional classpath -- right click on the project, select Properties, then Java Build Path, then Libraries. You can see sections for ModulePath and ClassPath.

The error message you were seeing is typical of running Java code as a module, but trying to call code that is not modularized. Either all your code has to be non-modularized (added to the ClassPath), or all has to be modularized (added to the ModulePath).

In Eclipse, all your code is added to the ClassPath, not the Module Path, so this should work -- and you don't have a `module-info.java` in your project, so it is not modularized. But for some reason, when running on Wildfly, part of the project is running as a module (maybe Wildfly itself?).

Honestly I don't know how to get this working, I have no experience with Wildfly at all. Is there a Wildfly mailing list you can ask on?

**Comment by lukehutch** [comment] 2020-05-03 21:46
Actually this line

```
java.lang.NoClassDefFoundError: io/github/classgraph/ClassGraph
```

may indicate that the problem is that ClassGraph is being loaded as a module by WildFly (since ClassGraph defines its own `module-info.class`), whereas your code is running on the traditional classpath. Possibly Wildfly is seeing the `module-info.class` and treating ClassGraph as a module automatically. But you can't call modular code from non-modular code.

Try deleting `versions/9/module-info.class` from the ClassGraph jar, and see if it fixes the problem.

If so, you need to find a way to force WildFly to add dependencies to the traditional classpath, rather than the module path. Or alternatively, you could add a `module-info.java` to your own project to modularize your code. You will need a `requires` entry in that file for each dependency, including ClassGraph: https://github.com/classgraph/classgraph/wiki#use-as-a-module

**Comment by MaverickLafont** [comment] 2020-05-03 22:58
I've learn something new today, i did not know modulePath and classPath, but you're right, my project is running classPath and not ModulePath. And if I understood correctly, my wildfly is running my project as a module and somehow it's making the exception.

I've tried to delete the module-info.class but the exception still remain.

The big issue is that this is a school project, and i will only give to my professor the code, not the server. So if i make change to it, it'll make things complicated.

Do you know any other way to get these animals ?

**Comment by lukehutch** [comment] 2020-05-03 23:04
The simple solution is to just run on JDK 8, since it does not have modules. That should fix it. But to solve the module vs. classpath problem, you'll have to ask the Wildfly community on a mailing list or StackOverflow. I have no idea really.

I'll close this, as it does not appear to be a ClassGraph bug. Sorry I couldn't help more, and bonne chance!

**Closed by lukehutch** 2020-05-03 23:04 UTC

**Comment by MaverickLafont** [comment] 2020-05-03 23:43
Thank you for your time. Have a great day !
