### ISSUE TITLE
whitelistJars with glob wildcard throws a StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sgijsenot** [classgraph/classgraph#348] opened 2019-05-16 05:47 UTC
Test case demonstrating the issue:
```
    ClassGraph classGraph = new ClassGraph().enableClassInfo().whitelistJars("whitelist*.jar");
    try (ScanResult scanResult = classGraph.scan()) {
      System.out.println(scanResult.getAllClasses().getNames());
    }
```

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1837)
	at nonapi.io.github.classgraph.scanspec.WhiteBlackList$WhiteBlackListWholeString.addToWhitelist(WhiteBlackList.java:271)
	at nonapi.io.github.classgraph.scanspec.WhiteBlackList$WhiteBlackListLeafname.addToWhitelist(WhiteBlackList.java:385)
	at io.github.classgraph.ClassGraph.whitelistJars(ClassGraph.java:820)
```

Seems this no longer works since version 4.8.27 and up. WhiteBlackList does not check for the presence of separatorChar before doing a substring based on its index.

**Comment by lukehutch** [comment] 2019-05-16 09:23
@sgijsenot Thanks for reporting this -- fixed and released in 4.8.36.

**Closed by lukehutch** 2019-05-16 09:23 UTC

**Comment by lukehutch** [comment] 2019-05-16 09:27
PS Sonatype is down currently, so the jar for 4.8.36 won't be available in Maven Central until this problem is fixed (you'll have to build ClassGraph from source using `mvn install` to build a snapshot of the git master version):

https://issues.sonatype.org/browse/OSSRH-41607

**Comment by sgijsenot** [comment] 2019-05-16 10:16
@lukehutch Thank you for the quick fix!

**Comment by lukehutch** [comment] 2019-05-16 11:12
> @lukehutch Thank you for the quick fix!

You're welcome -- [that is the goal](https://github.com/classgraph/classgraph/blob/master/Zero-Bugs-Commitment.md).

Please let me know if the problem is solved for your usecase.
